### ISSUE TITLE
Error: `SyntaxError: Unexpected token: name`

### ISSUE THREAD

**Issue by mimshins** [terser/terser#1325] opened 2022-12-24 18:33 UTC
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
5.14.2

**Complete CLI command or `minify()` options used**
```ts
const result = await minify(
  source,
  isESModule
    ? {
        module: isESModule,
        compress: { module: isESModule },
        mangle: { module: isESModule }
      }
    : undefined
);
```

**`terser` input**

```ts
export * as Breadcrumb from "./Breadcrumb";
```

**`terser` output or error**

`SyntaxError: Unexpected token: name (Breadcrumb)`

**Expected result**

Obviously not an Error :-"

**Comment by fabiosantoscode** [comment] 2023-01-02 14:16
Hello! This is a duplicate of #1231

**Closed by fabiosantoscode** 2023-01-02 14:16 UTC
