### ISSUE TITLE
minify in phpstorm with Terser 4.6.4

### ISSUE THREAD

**Issue by gtraxx** [terser/terser#576] opened 2020-02-26 23:14 UTC
Hi :)
Bug report or Feature request? Feature request

Version (complete output of terser -V or specific git commit) 4.6.4
OS : mac osx Hight Sierra
Complete CLI command or minify() options used

```
/Users/aureliengerits/.npm-global/lib/node_modules/terser/bin/terser /Users/aureliengerits/PhpstormProjects/yunabeatsrecords/skin/yunabeats/js/src\global.js --comments -o global.min.js
ERROR: ENOENT: no such file or directory, open '/Users/aureliengerits/PhpstormProjects/yunabeatsrecords/skin/yunabeats/js/src\global.js'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at read_file (/Users/aureliengerits/.npm-global/lib/node_modules/terser/bin/terser:354:19)
    at /Users/aureliengerits/.npm-global/lib/node_modules/terser/bin/terser:177:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/aureliengerits/.npm-global/lib/node_modules/terser/bin/terser:176:28)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

Process finished with exit code 1
```

**Comment by fabiosantoscode** [comment] 2020-02-27 12:06
Hello there!

Please describe your issue in detail.

However, whatever the issue is, mac OS won't like the backslash in `src\global.js`.

**Comment by gtraxx** [comment] 2020-02-27 13:19
Hi, I'll check, but the watchers (PHP Storm) are actually optimized for Windows
Thanks :)

**Comment by L2jLiga** [comment] 2020-02-27 13:21
If issue relates to given path to file then it can be handled on Terser side by using `path.normalize`

**Comment by fabiosantoscode** [comment] 2020-02-27 13:23
You'll want to file an issue with them :)

However someone could create a nice module for dealing with user errors while reading a path. It would try to open a file, and if it fails, it tries massaging backslashes and things to find the actual path, then emits a warning "hey you typed your path for windows, please change". I would be happy to use such a module.

**Comment by fabiosantoscode** [comment] 2020-02-27 13:24
Case insensitive file systems like Mac OS's default and Windows's default cause issues when deploying to production (or when I use someone else's stuff on my Linux laptop)

**Comment by L2jLiga** [comment] 2020-02-27 13:30
> However someone could create a nice module for dealing with user errors while reading a path.

Sounds interesting, what you expect from such module? Try to find file case-insensetive independent of FS and OS? Try to fix backslashes? Anything else?

> it tries massaging backslashes and things to find the actual path

Can be done by built-in [`path.normalize`](https://nodejs.org/api/path.html#path_path_normalize_path)

> Case insensitive file systems like Mac OS's default and Windows's default 

Actually Windows default file system (NTFS) case sensitive while OS itself makes it insensitive

**Comment by L2jLiga** [comment] 2020-02-27 13:49
Another option I see is try to use [`glob`](https://npmjs.org/package/glob):

```javascript
var glob = require("glob")

glob("**/packAge.jsoN", { nocase: true }, function (er, files) {
  console.log(files) // ["package.json", "system/node_modules/ecma-utils/package.json", …]
})
```

you can check this example on [RunKit](https://npm.runkit.com/glob)

**Comment by fabiosantoscode** [comment] 2020-02-27 15:04
path.normalize doesn't fix this on Linux. It's just that on windows you can use \ or /, so normalize can fix it.

glob sounds promising.

Maybe this is better fixed at the module bundler level, idk.

**Comment by fabiosantoscode** [comment] 2020-02-27 16:25
I don't really like packages which are split up, so I don't want to make other people suffer from the same.

I'm really focused on CPU/ram savings atm. Good news is, I have some CPU improvements and ram improvements will follow :)

**Comment by eserini** [comment] 2020-06-29 08:22
@gtraxx  

I have PHPStorm on Linux (Ubuntu 20.04), i installed it with: 

`npm install terser -g`

for command line use, then on the File Watcher window:

File Type: `JavaScript`
Scope: `All Places`
Program: `/usr/local/lib/node_modules/terser/bin/terser`
Arguments: `$FileName$ --compress --mangle --output $FileNameWithoutExtension$.min.js`
Output paths to refresh: `$FileNameWithoutExtension$.min.js`
Working directory: `$FileDir$`

and it works like a charm, maybe this helps?

**Comment by fabiosantoscode** [comment] 2021-11-14 17:05
I'm guessing PHPStorm fixed this internally, and stopped forwarding `\` as path separators outside of windows? In this case we can close the issue.

**Closed** 2022-12-01 21:12 UTC
Labels: bug
