### ISSUE TITLE
Add shortcuts to global vars (i.e. window/document)

### ISSUE THREAD

**Issue by pimlie** [terser/terser#459] opened 2019-09-14 13:08 UTC
**~~Bug report or~~ Feature request?**

**Version (complete output of `terser -V` or specific git commit)**
terser 4.3.1

**Complete CLI command or `minify()` options used**
`terser ./dom.js -mc --toplevel`

**`terser` input**
```js
document.createElement('test')
document.getElementById('test')
document.title
document.querySelector('#test')
```

**`terser` output or error**
```js
document.createElement("test"),document.getElementById("test"),document.title,document.querySelector("#test");
```

**Expected result**
```
var e=document;e.createElement("test"),e.getElementById("test"),e.title,e.querySelector("#test");
```

**More info**

Maybe this is configurable already but couldnt find anything when searching the docs. It should be possible to just shortcut the vars `window` or `document` as their names are quite long. Seems that this only provides a lesser size when eg `document` is used more then twice.

**Comment by fabiosantoscode** [comment] 2019-09-14 15:48
This is not something we want to do.

The problem is that the global variable might be reassigned at any point during the execution of the program, and Terser doesn't have much intelligence in the way of knowing which variables aren't reassignable or when they are reassigned.

The best way for you to do this is to declare and use the variable yourself or use an IIFE that declares it.

**Closed by fabiosantoscode** 2019-09-14 15:48 UTC
