### ISSUE TITLE
Simple assignments to let binding prevent removal of binding

### ISSUE THREAD

**Issue by mischnic** [terser/terser#1162] opened 2022-03-03 21:07 UTC
**Bug report or Feature request?**

suboptimal code/feature request

**Version (complete output of `terser -V` or specific git commit)**

terser 5.12.0

**Complete CLI command or `minify()` options used**

`terser -mc passes=10`

**`terser` input**

```
(()=>{console.log(1);let s="asdsda";s="asdasdsdasdasd"})();
```

**`terser` output or error**

(same as input)

**Expected result**

With `var` instead of `let`, the output is `console.log(1);`

**Comment by jridgewell** [comment] 2022-03-03 21:18
Thanks for the report! Marking this as a duplicate of https://github.com/terser/terser/issues/572.

**Closed by jridgewell** 2022-03-03 21:18 UTC
