### ISSUE TITLE
Non-optimal code produced

### ISSUE THREAD

**Issue by Hideman85** [terser/terser#1122] opened 2021-11-30 18:10 UTC
I'm currently looking for optimizing our app bundle and I'm concerns about something.
Somehow Terser are not able to compress a function name, the function does not access to any proto nor to any this context.
I'm not so sure what is the source library I would think it is probably sentry sdk (error reporting tool)
Edit: Could also be aws-sdk the KMSKey for me sounds like their server side encryption.

<details>
  <summary>Minified result</summary>
  
> ```function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Nl||(Nl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ll||(Ll={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Rl||(Rl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Fl||(Fl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Bl||(Bl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ul||(Ul={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(zl||(zl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Hl||(Hl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Yl||(Yl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Vl||(Vl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Wl||(Wl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ql||(ql={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Kl||(Kl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Gl||(Gl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}($l||($l={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Zl||(Zl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Xl||(Xl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Jl||(Jl={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ql||(Ql={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(eu||(eu={})),function(e){e.visit=function(e,t){return void 0!==e.Prefix?t.Prefix(e.Prefix):void 0!==e.Tag?t.Tag(e.Tag):void 0!==e.And?t.And(e.And):t._(e.$unknown[0],e.$unknown[1])},e.filterSensitiveLog=function(e){var t;return void 0!==e.Prefix?{Prefix:e.Prefix}:void 0!==e.Tag?{Tag:Pc.filterSensitiveLog(e.Tag)}:void 0!==e.And?{And:eu.filterSensitiveLog(e.And)}:void 0!==e.$unknown?((t={})[e.$unknown[0]]="UNKNOWN",t):void 0}}(tu||(tu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(nu||(nu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ru||(ru={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(iu||(iu={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.Filter&&{Filter:tu.filterSensitiveLog(e.Filter)})}}(ou||(ou={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.Rules&&{Rules:e.Rules.map((function(e){return ou.filterSensitiveLog(e)}))})}}(au||(au={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.ReplicationConfiguration&&{ReplicationConfiguration:au.filterSensitiveLog(e.ReplicationConfiguration)})}}(su||(su={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(cu||(cu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(lu||(lu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(uu||(uu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(du||(du={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(fu||(fu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(hu||(hu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(pu||(pu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(mu||(mu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(gu||(gu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(vu||(vu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(yu||(yu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(bu||(bu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(_u||(_u={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(wu||(wu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(xu||(xu={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.SSEKMSKeyId&&{SSEKMSKeyId:Cn})}}(Tu||(Tu={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.SSECustomerKey&&{SSECustomerKey:Cn})}}(Su||(Su={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ku||(ku={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Eu||(Eu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Cu||(Cu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Au||(Au={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ju||(ju={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Pu||(Pu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Mu||(Mu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ou||(Ou={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Du||(Du={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Iu||(Iu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Nu||(Nu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Lu||(Lu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ru||(Ru={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Fu||(Fu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Bu||(Bu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Uu||(Uu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(zu||(zu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Hu||(Hu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Yu||(Yu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Vu||(Vu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Wu||(Wu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(qu||(qu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ku||(Ku={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Gu||(Gu={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.SSEKMSKeyId&&{SSEKMSKeyId:Cn})}}($u||($u={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.SSECustomerKey&&{SSECustomerKey:Cn})}}(Zu||(Zu={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.AnalyticsConfigurationList&&{AnalyticsConfigurationList:e.AnalyticsConfigurationList.map((function(e){return Rc.filterSensitiveLog(e)}))})}}(Xu||(Xu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ju||(Ju={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Qu||(Qu={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ed||(ed={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.InventoryConfigurationList&&{InventoryConfigurationList:e.InventoryConfigurationList.map((function(e){return sl.filterSensitiveLog(e)}))})}}(td||(td={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(nd||(nd={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.MetricsConfigurationList&&{MetricsConfigurationList:e.MetricsConfigurationList.map((function(e){return Cl.filterSensitiveLog(e)}))})}}(rd||(rd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(id||(id={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(od||(od={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ad||(ad={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(sd||(sd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(cd||(cd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ld||(ld={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ud||(ud={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(dd||(dd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(fd||(fd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(hd||(hd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(pd||(pd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(md||(md={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(gd||(gd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(vd||(vd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(yd||(yd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(bd||(bd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(_d||(_d={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(wd||(wd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(xd||(xd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Td||(Td={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Sd||(Sd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(kd||(kd={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.AnalyticsConfiguration&&{AnalyticsConfiguration:Rc.filterSensitiveLog(e.AnalyticsConfiguration)})}}(Ed||(Ed={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Cd||(Cd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Ad||(Ad={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.ServerSideEncryptionConfiguration&&{ServerSideEncryptionConfiguration:Wc.filterSensitiveLog(e.ServerSideEncryptionConfiguration)})}}(jd||(jd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Pd||(Pd={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.InventoryConfiguration&&{InventoryConfiguration:sl.filterSensitiveLog(e.InventoryConfiguration)})}}(Md||(Md={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.Rules&&{Rules:e.Rules.map((function(e){return gl.filterSensitiveLog(e)}))})}}(Od||(Od={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.LifecycleConfiguration&&{LifecycleConfiguration:Od.filterSensitiveLog(e.LifecycleConfiguration)})}}(Dd||(Dd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Id||(Id={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Nd||(Nd={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.MetricsConfiguration&&{MetricsConfiguration:Cl.filterSensitiveLog(e.MetricsConfiguration)})}}(Ld||(Ld={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Rd||(Rd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Fd||(Fd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Bd||(Bd={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.ReplicationConfiguration&&{ReplicationConfiguration:au.filterSensitiveLog(e.ReplicationConfiguration)})}}(Ud||(Ud={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(zd||(zd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Hd||(Hd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Yd||(Yd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Vd||(Vd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Wd||(Wd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(qd||(qd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Kd||(Kd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Gd||(Gd={})),function(e){e.filterSensitiveLog=function(e){return he(he(he({},e),e.SSEKMSKeyId&&{SSEKMSKeyId:Cn}),e.SSEKMSEncryptionContext&&{SSEKMSEncryptionContext:Cn})}}($d||($d={})),function(e){e.filterSensitiveLog=function(e){return he(he(he(he({},e),e.SSECustomerKey&&{SSECustomerKey:Cn}),e.SSEKMSKeyId&&{SSEKMSKeyId:Cn}),e.SSEKMSEncryptionContext&&{SSEKMSEncryptionContext:Cn})}}(Zd||(Zd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Xd||(Xd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Jd||(Jd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(Qd||(Qd={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(ef||(ef={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(tf||(tf={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(nf||(nf={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(rf||(rf={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(of||(of={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(af||(af={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(sf||(sf={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(cf||(cf={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(lf||(lf={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(uf||(uf={})),function(e){e.filterSensitiveLog=function(e){return he({},e)}}(df||(df={})),function(e){e.filterSensitiveLog=function(e){return he(he({},e),e.KMSKeyId&&{KMSKeyId:Cn})}}(ff||(ff={}));function hf(e)```

</details>

I did used the default options of latest version of terser, input ecma 8 out ecma 6.

**Comment by fabiosantoscode** [comment] 2022-04-09 16:46
This looks like a duplicate of #790, as there are a lot of duplicated 

`function(e){e.filterSensitiveLog=function(e){return he({},e)}`

But it's hard to know without looking at the source.

**Comment by fabiosantoscode** [comment] 2022-11-24 11:46
I did some digging, and this appears to be a part of an S3 package.

Here's the commit that added all of these (control+f for it, you'll see tons of them)

https://github.com/aws/aws-sdk-js-v3/commit/8eff0875580e30e12f2e0abd5fa402973790e697.diff

There's some compiler code in that package, that ensures all filterSensitiveLog functions are placed together at the bottom (the package is built with code generation). This is why we're seeing such repetitive code.

https://github.com/aws/aws-sdk-js-v3/blob/33e68228fb64c53dd8f89e6be76dd5f46edc3cfd/scripts/generate-clients/code-ordering.js

The repeated variations of `(Ll||(Ll={}))` is usually how Typescript extends namespaces and other things. The `LI ||` check ensures the namespace doesn't exist, and `LI = {}` creates an empty namespace.

**Closed by fabiosantoscode** 2022-11-24 11:46 UTC
