### ISSUE TITLE
Remove variables that are not read

### ISSUE THREAD

**Issue by Knagis** [terser/terser#826] opened 2020-09-15 19:11 UTC
**Feature request**
Remove variables where the value is never read, when it is assigned outside of the declaration.

**Version**
try.terser.org @ 2020.09.15

**Complete CLI command or `minify()` options used**
default options

**`terser` input**

```js
function f1() {
  let x = 2;
}
 
function f2() {
  let x;
  x = 2;
}
```

**`terser` output**

```js
function f1(){}function f2(){let f;f=2}
```

**Expected result**
```js
function f1(){}function f2(){}
```

**Comment by fabiosantoscode** [comment] 2020-09-17 01:11
Interesting. Thanks for reporting!

**Comment by jridgewell** [comment] 2021-09-06 22:02
Closing as a duplicate of https://github.com/terser/terser/issues/572.

**Closed by jridgewell** 2021-09-06 22:02 UTC
Labels: enhancement, suboptimal-output
