### ISSUE TITLE
support static block syntax

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#1136] opened 2022-01-23 02:30 UTC
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

5.10.0

**Complete CLI command or `minify()` options used**

default

**`terser` input**

```js
class A {
    static { }
}
```

**`terser` output or error**

```
Unexpected token: punc ({)
```

**Expected result**

That's already stage 4, supported by nodejs, browser and acorn (v8.5.0)

**Comment by michael42** [comment] 2022-02-12 10:16
It seems to me that's a duplicate of #1093.

**Closed** 2022-02-17 06:49 UTC
