### ISSUE TITLE
Add a mapping for the end of a function's body to the sourcemap

### ISSUE THREAD

**Issue by hbenl** [terser/terser#1210] opened 2022-06-14 15:08 UTC
**Feature request**
I have repeatedly seen an issue where stepping to the end of a function in a debugger seems to stop at the wrong line of code. For me this is the most common issue where debugging became confusing because the sourcemap wasn't detailed enough.

**Version**
terser 5.14.1

**Complete CLI command**
terser index.js -o out.js --compress --source-map \"url='out.js.map',includeSources\"

**`terser` input**
```javascript
function fn(foo) {
  if (!foo) {
    return "Bar";
  }
  return "Foo";
}
console.log(/*#__NOINLINE__*/fn(true));
```

**STR**
- clone https://github.com/hbenl/terser-sourcemap-issue
- run `npm install` and `npm run build`
- open the folder in VS Code
- set a breakpoint in `index.js` at line 2
- start the debugger
- press "Step over"

Now the debugger shows that we're paused at line 3:
![Screenshot from 2022-06-14 16-42-55](https://user-images.githubusercontent.com/16060807/173610499-9ea003fe-250c-44ec-b5f5-1dc131a51999.png)

**Expected result**
We shouldn't hit that line because, as the variables panel shows, `foo` is `true` and the return value of the function is `'Foo'`, so we should really be paused at line 5.

To see why this is happening try executing the generated code:
- set the `sourceMaps` option in `.vscode/launch.json` to `false`
- set a breakpoint in `out.js` at line 1
- start the debugger
- press "Step over"

Now the debugger shows that we're paused at the very end of the function (after `"Bar"`):
![Screenshot from 2022-06-14 16-44-46](https://user-images.githubusercontent.com/16060807/173610730-a92e40e9-f4fd-4e49-b44f-2b42eac28668.png)

Here's the sourcemap visualized with https://evanw.github.io/source-map-visualization/:
![Screenshot from 2022-06-14 16-46-13-cropped](https://user-images.githubusercontent.com/16060807/173610821-98ab4752-7e86-40c4-afb2-0c4c36fc4097.png)
As you can see there is no mapping for the end of the function, so the debugger uses the preceding mapping, which maps `"Bar"` to line 3 in `index.js`.

If `terser` added a mapping for the end of the function body (the closing `}`), the debugger could map the last location correctly.

**Comment by jridgewell** [comment] 2022-06-14 19:54
I believe this is a duplicate of https://github.com/terser/terser/issues/1163?

**Comment by jridgewell** [comment] 2022-06-15 17:34
That is frustrating. I'm going to close this as a duplicate of #1163, and will post updates there.

**Closed by jridgewell** 2022-06-15 17:34 UTC
