### ISSUE TITLE
`compress.evaluate` option works incorrectly

### ISSUE THREAD

**Issue by anseki** [terser/terser#873] opened 2020-11-17 03:58 UTC
(Sorry, my English is poor.)
Hi, thank you for the useful library.

The `compress.evaluate` option seems to make a code become big in some cases.

**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 5.4.0

**Complete CLI command or `minify()` options used**
`minify(code, {toplevel: true})`

**`terser` input**
```js
const LABEL = 'My App';

console.log(`[${LABEL}] 0`);
console.log(`[${LABEL}] 1`);
console.log(`[${LABEL}] 2`);
console.log(`[${LABEL}] 3`);
console.log(`[${LABEL}] 4`);
console.log(`[${LABEL}] 5`);
console.log(`[${LABEL}] 6`);
console.log(`[${LABEL}] 7`);
console.log(`[${LABEL}] 8`);
console.log(`[${LABEL}] 9`);
console.log(`[${LABEL}] A`);
console.log(`[${LABEL}] B`);
console.log(`[${LABEL}] C`);
console.log(`[${LABEL}] D`);
console.log(`[${LABEL}] E`);
console.log(`[${LABEL}] F`);
```

**`terser` output or error**
All `${LABEL}`s were replaced. Then 416 bytes.
```js
console.log("[My App] 0"),console.log("[My App] 1"),console.log("[My App] 2"),console.log("[My App] 3"),console.log("[My App] 4"),console.log("[My App] 5"),console.log("[My App] 6"),console.log("[My App] 7"),console.log("[My App] 8"),console.log("[My App] 9"),console.log("[My App] A"),console.log("[My App] B"),console.log("[My App] C"),console.log("[My App] D"),console.log("[My App] E"),console.log("[My App] F");
```

**Expected result**
Result: 401 bytes.
```js
const o="My App";console.log(`[${o}] 0`),console.log(`[${o}] 1`),console.log(`[${o}] 2`),console.log(`[${o}] 3`),console.log(`[${o}] 4`),console.log(`[${o}] 5`),console.log(`[${o}] 6`),console.log(`[${o}] 7`),console.log(`[${o}] 8`),console.log(`[${o}] 9`),console.log(`[${o}] A`),console.log(`[${o}] B`),console.log(`[${o}] C`),console.log(`[${o}] D`),console.log(`[${o}] E`),console.log(`[${o}] F`);
```

The result above is returned by `minify(code, {toplevel: true, compress: {evaluate: false}})`

If the `const LABEL = 'My App';` is replaced with `const LABEL = 'My Application';`, the replacing is prevented. But I don't know how the Terser decide it.

**Comment by fabiosantoscode** [comment] 2020-11-19 10:46
Hey there!

This a duplicate of #790, which is a duplicate of an even older issue that I can't find.

`evaluate` doesn't take into account other inlining sites. The reason it doesn't replace a longer string is because of the literal length of the variable name :) (even if mangle is enabled). Rename your variable `MY_SUPER_LONG_LABEL` and watch "My Application" be inlined all the time.

**Closed by fabiosantoscode** 2020-11-19 10:46 UTC

**Comment by anseki** [comment] 2020-11-19 12:06
Thank you! :smile:
