### ISSUE TITLE
`eval` calls not inlined

### ISSUE THREAD

**Issue by darkwebdev** [terser/terser#455] opened 2019-09-11 13:34 UTC
**Bug report or Feature request?**

Code is super-sub-optimal, but correct (but useless, cause you don't need terser for it). So I think it's a bug.

**Version (complete output of `terser -V` or specific git commit)**
`terser 4.3.0`

**Complete CLI command or `minify()` options used**
```
terser -c passes=2 -m eval=true
```

**`terser` input**

```
const f2 = () => {
  const a = eval('/./');
  return a
}
```

**`terser` output or error**
```
const n=()=>{const e=eval("/./");return e};
```

**Expected result**
```
const n=()=>eval("/./");
```

**Comment by fabiosantoscode** [comment] 2019-09-13 17:48
Interesting.

Terser has good reason to avoid minifying things with eval in them, but I think something can be done for this case. Thanks for the report!

**Comment by darkwebdev** [comment] 2019-09-14 18:43
Yes, I agree that `eval`s can be dangerous, but I only need optimization outside of it. If I replace `eval` with `Regexp` everything works:
before:
```
const f2 = () => {
  const a = new Regexp('.');
  return a
}
```
after:
```
const n=()=>new Regexp(".");
```
So it looks like Terser treats `eval` somehow specially.

Thanks!

**Comment by kzc** [comment] 2019-09-14 21:23
This is working as designed. I would not recommend altering the current minifier behavior. Any code optimization or mangling of variables and function names can break code involving `eval` since it accesses the current scope and all parent scopes - nevermind the security implications.  `eval` and the `with` clause are constructs to be avoided.

Details and potential workarounds discussed here:

https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval

**Comment by fabiosantoscode** [comment] 2019-09-17 15:04
Thanks for your input @kzc. You have a point. I'm closing this.

Although I do love eval from the bottom of my heart.

**Closed by fabiosantoscode** 2019-09-17 15:04 UTC
Labels: enhancement, help wanted
