### ISSUE TITLE
>= v5.2.0: increase in minified sizes

### ISSUE THREAD

**Issue by XhmikosR** [terser/terser#822] opened 2020-09-10 10:44 UTC
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**

**Complete CLI command or `minify()` options used**

**`terser` input**

**`terser` output or error**

**Expected result**

Initially noticed here: https://github.com/twbs/bootstrap/pull/31600#issuecomment-687295462

Basically after v5.2.0 the dist files are quite bigger than what they were before. Sorry for not filling up the issue template, not sure how to make a small reproducible test sample.

It happens with our main branch since terser v5.2.0.

**Comment by fabiosantoscode** [comment] 2020-09-10 18:43
Hey there!

This bundlewatch thing looks sweet :)

I don't see such a big increase, it looks like a 300 bytes increase. In terms of percentage it's not much.

You can expect this kind of fluctuation in file size across versions (as Terser grows more optimizations and cuts back on others to fix bugs), but I'll have a look and see if it's worth considering a real regression.

**Comment by XhmikosR** [comment] 2020-09-10 18:47
Yeah, "big" might be an overstatement, it's just that all this time we struggle to keep size small :)

Thanks for taking a look!

**Comment by XhmikosR** [comment] 2020-09-10 18:48
BTW the size diff is in gzip.

**Comment by XhmikosR** [comment] 2020-11-02 08:19
@fabiosantoscode just a friendly ping in case you forgot about this 🙂 The increase is quite big because the bundlewatch diff refers to gzip sizes.

**Comment by XhmikosR** [comment] 2021-04-12 03:46
@fabiosantoscode friendly ping. I'd really appreciate it if you could have a look at this issue :)

It seems the issue is still present. Note that this affects the gzip compressed files. I also tested uglify-js and it also has an increase in size, but less than terser.

I've pinned terser to 5.1.1 for months now and I'd like to be able to update to the latest one to get any further fixes.

Summary:

* terser 5.1.1 (main branch): https://ja2r7.app.goo.gl/MZC9X4WSVp5neYX87
* terser 5.6.1: https://ja2r7.app.goo.gl/weVnZxV4Pb1hd3Ht8
* uglify-js 3.13.4: https://ja2r7.app.goo.gl/6i1Yw4gnXuGpjur37

Thanks in advance!

**Comment by XhmikosR** [comment] 2021-09-14 06:28
@fabiosantoscode friendly ping :) This still happens with 5.8.0. Also, please check the above comment since it seems to have pinpointed the offending change.

**Comment by fabiosantoscode** [comment] 2021-09-14 10:55
Hello!

Thanks to @alpadev for checking this out with more libraries and finding a commit.

I'm closing this because a tiny increase in bytes in some libraries is not a big deal indeed.

Thank you!

**Closed by fabiosantoscode** 2021-09-14 10:55 UTC

**Comment by XhmikosR** [comment] 2021-09-16 15:19
@fabiosantoscode thanks for the reply. That being said, I really hope you reconsider. Because JavaScript files on the web are served compressed (if not, they should be), any change that improves the compressed filesize is more than welcome. AFAICT the newer terser versions offer better uncompressed size, but the compressed size is worse.

Now, you may think 2 or even 5% is not big and I agree up to some level, but again, here I think everyone is aiming for the best results that's why we need to use a minifier in the first place :).

That being said, I haven't tested brotli, but gzip shows clearly a regression.
