### ISSUE TITLE
[bug] strings are not reused as variables if variable names too long

### ISSUE THREAD

**Issue by SeregPie** [terser/terser#321] opened 2019-03-29 15:56 UTC
**report**

Check out the codepen.
https://codepen.io/SeregPie/pen/xeKVvR
The same string appears multiple times in the minified code but in the original code it is declared only once.
If I rename the variables and make them shorter, it produces the correct minified code.

**version**

3.17.0

**options**

`{toplevel: true}`

**input**

```js
let lowerCasedAlphabetic = 'abcdefghijklmnopqrstuvwxyz';
let upperCasedAlphabetic = lowerCasedAlphabetic.toUpperCase();
let alphabetic = lowerCasedAlphabetic + upperCasedAlphabetic;
let numeric = '0123456789';
let alphanumeric = alphabetic + numeric;

Object.assign({}, {
  lowerCasedAlphabetic,
  upperCasedAlphabetic,
  alphabetic,
  numeric,
  alphanumeric,
});
```

**output**

```js
let e='abcdefghijklmnopqrstuvwxyz'.toUpperCase(),a='abcdefghijklmnopqrstuvwxyz'+e,p=a+'0123456789';Object.assign({},{lowerCasedAlphabetic:'abcdefghijklmnopqrstuvwxyz',upperCasedAlphabetic:e,alphabetic:a,numeric:'0123456789',alphanumeric:p});
```

**Comment by fabiosantoscode** [comment] 2019-05-19 14:07
Interesting behaviour, but suboptimal code is not a bug. Maybe someone has the time to look into this. I don't know what might be causing it.

**Comment by iosio** [comment] 2019-10-18 17:30
Would be nice to be able to opt out of this behavior.

**Comment by fabiosantoscode** [comment] 2020-02-23 14:23
If a fix is implemented, there will be no need to opt out. It's just that it's a bit hard to implement so I'm not really prioritising it.

The reason behind this is that Terser checks "how long" the result will be but doesn't take mangling into account. Taking mangling into account the traditional way would be very inefficient, so the fix I want to implement is adding a way for Terser to find out just how long a node is without turning it into a string. For example, `false` through this magic function would return 5. The number `100` would return 3. And your variables would return `1` or `2` to take mangling into account. This would make terser choose to reuse the string as a variable for you. No option needed.

**Comment by fabiosantoscode** [comment] 2020-02-24 13:05
I went ahead and started implementing it :) It was easier than I thought to get the basics, but it doesn't take parentheses into account, which I still have to fix.

**Comment by fabiosantoscode** [comment] 2023-04-19 09:35
Has been fixed in the meantime!

**Closed by fabiosantoscode** 2023-04-19 09:35 UTC
Labels: suboptimal-output
