### ISSUE TITLE
Variable name collisions when inlining

### ISSUE THREAD

**Issue by overlookmotel** [terser/terser#639] opened 2020-04-08 16:45 UTC
**Bug report or Feature request?**

Bug.

**Version (complete output of `terser -V` or specific git commit)**

`terser 4.6.11`

(bug also present on 4.6.10, but I've not tested other versions)

**Complete CLI command or `minify()` options used**

```
terser input.js --toplevel --compress --beautify
```

**`terser` input**

```js
const path = require('path');

module.exports = function getExtFn() {
  return function(path) {
    return getExt(path);
  }
}

function getExt(name) {
  let ext;
  if (!ext) {
    ext = getExtInner(name);
  }
  return ext;
}

function getExtInner(name) {
  return path.extname(name);
}
```

**`terser` output or error**

```js
const path = require("path");

module.exports = function() {
    return function(path) {
        return function(name) {
            let ext;
            ext || (ext = function(name) {
                return path.extname(name);
            }(name));
            return ext;
        }(path);
    };
};
```

**Expected result**

The innermost function's `path.extname(name)` should reference top level `path` not the scope of one of its enclosing functions.

Removing `--compress` solves the problem, but results in longer code.

Changing one of the var names from `path` also solves it, so cause is presumably a failure to spot the name collision.

**Comment by fabiosantoscode** [comment] 2020-04-08 18:01
Great issue, thanks! I'll have a look tonight after work. I really do appreciate the time you went though to make this small reproducible report :heart:

**Comment by fabiosantoscode** [comment] 2020-04-08 18:01
Workaround is to remove either `inline` or `reduce_vars` (not sure which yet because I haven't debugged)

**Comment by overlookmotel** [comment] 2020-04-08 20:18
No worries! I was glad at least the bug turned out not due to a mistake in my own code.

My workaround for now is just to change the name of one of the variables.

**Comment by fabiosantoscode** [comment] 2020-04-08 22:50
I found the issue. Basically, when `getExt` gets inlined, Terser doesn't update its scope information. Afterwards, `getExtInner` is inlined right into it even though there's a new `path` variable outside of it now.

**Comment by fabiosantoscode** [comment] 2020-04-08 22:51
I found a solution, which I don't like because it lowers compression rate. So instead I'm going to add this fix on top of my current work to improve inlining in general.

**Comment by overlookmotel** [comment] 2020-04-08 23:14
That makes sense. Well don't hurry a fix for my sake. Changing the variable names worked for me. I just wanted to file a report since I found it...

Incidentally, the output code could also be optimized a little bit more.

`(ext = function(name) { return path.extname(name); }(name))`

could be squeezed down to just:

`(ext = path.extname(name))`

Obviously my example input code is totally ridiculous though! No-one in their right mind would write that, so not worth much effort optimizing for it. Though I suppose you could end up with something like that if `__DEV__`-fenced code had been stripped out by Babel before it reaches terser.

Thanks for your fantastic work on terser.

**Comment by fabiosantoscode** [comment] 2020-04-09 00:05
No, I figured since you only found out about this bug now it's hard for someone else to also find this :)

There's always more optimization to do :) if the input code is weird (in this case `let ext; if (ext)`) the output code being a little suboptimal is not such a big deal. Hopefully our code is mostly awesome! :D

**Comment by fabiosantoscode** [comment] 2020-05-17 16:44
This fix will be out in Terser 5. I will be releasing alphas of it in a few weeks.

**Comment by fabiosantoscode** [comment] 2020-07-05 16:26
Terser 5 does not fix this yet.

**Comment by fabiosantoscode** [comment] 2020-07-05 16:27
There's a beta version for v5 you can use, which will be released as mainline soon. `npm install terser@beta`.

**Comment by fabiosantoscode** [comment] 2020-08-18 02:05
Terser 5 has been released so I can close this one.

**Closed by fabiosantoscode** 2020-08-18 02:05 UTC
Labels: bug

**Comment by overlookmotel** [comment] 2020-08-18 19:15
Thanks Fabio!
