### ISSUE TITLE
arrows and unsafe_arrows have no effect

### ISSUE THREAD

**Issue by jantimon** [terser/terser#1154] opened 2022-02-24 07:06 UTC
**Bug report**

`unsafe_arrows` will not convert `function() { }` to `() => {}`

From the docs https://terser.org/docs/api-reference.html

> `unsafe_arrows` (default: `false`) -- Convert ES5 style anonymous function expressions to arrow functions if the function body does not reference this. Note: it is not always safe to perform this conversion if code relies on the the function having a prototype, which arrow functions lack. This transform requires that the `ecma` compress option is set to 2015 or greater.

However if you try this on the Terser_REPL or with the latest cli you will see that it won't minify functions.

**`terser` input**

```js
function x() {
  
}

window.z = x
```

**`terser` output or error**

```js
window.z=function(){};
```

**Expected result**

```js
window.z=()=>{};
```

<img width="741" alt="Terser_REPL" src="https://user-images.githubusercontent.com/4113649/155474309-4bba0279-4d1f-4a7f-a339-baa50e895fab.png">

**Comment by fabiosantoscode** [comment] 2022-02-26 18:15
Hello there!

I can reproduce this, but this happens due to the fact that `unsafe_arrows` will ignore your function declaration (it's only interested in anonymous functions) and it only gets inlined after.

This can be fixed by adding a second pass with the `passes` compress option.

**Closed by fabiosantoscode** 2022-02-26 18:15 UTC

**Comment by jantimon** [comment] 2022-02-26 19:00
Thanks `passes: 2` fixed it :)
