### ISSUE TITLE
Can not preserve all comments with "--comments all"

### ISSUE THREAD

**Issue by imaegoo** [terser/terser#1008] opened 2021-06-11 02:38 UTC
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

5.7.0

**Complete CLI command or `minify()` options used**

``` sh
terser --comments all -- input.js>output.js
```

**`terser` input**

``` js
;// START_TAG_FOR_2;
console.log(2);
;// END_TAG_FOR_2;

;// START_TAG_FOR_3;
console.log(3);
;// END_TAG_FOR_3;
```

**`terser` output or error**

``` js
// START_TAG_FOR_2;
console.log(2);// START_TAG_FOR_3;
console.log(3);// END_TAG_FOR_3;
```

**Expected result**

Possibily...

``` js
// START_TAG_FOR_2;
console.log(2);// END_TAG_FOR_2;
// START_TAG_FOR_3;
console.log(3);// END_TAG_FOR_3;
```

**Comment by imaegoo** [comment] 2021-06-11 03:01
**`terser` input**



``` js
;/** @preserve START_TAG_FOR_2 */;
console.log(2);
;/** @preserve END_TAG_FOR_2 */;

;/** @preserve START_TAG_FOR_3 */;
console.log(3);
;/** @preserve END_TAG_FOR_3 */;
```

```
npx terser@5.7.0 -- input.js>output.js
# or
npx terser@5.7.0 --comments all -- input.js>output.js
```

**`terser` output or error**

``` js
console.log(2);console.log(3);
```

**Expected result**

Comments keep.

**Comment by jridgewell** [comment] 2021-09-19 05:58
Closing as a duplicate of https://github.com/terser/terser/issues/575.

**Closed by jridgewell** 2021-09-19 05:58 UTC
