### ISSUE TITLE
Unexpected token: eof (undefined) during uglify'ing 

### ISSUE THREAD

**Issue by devdemi** [terser/terser#684] opened 2020-05-01 16:15 UTC
Error during uglify'ing  my project 
```
 - broccoliBuilderErrorStack: SyntaxError: Unexpected token: eof (undefined)
    at ee (/usr/src/fe/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/usr/src/fe/node_modules/terser/dist/bundle.min.js:1:28031)
    at l (/usr/src/fe/node_modules/terser/dist/bundle.min.js:1:28122)
    at f (/usr/src/fe/node_modules/terser/dist/bundle.min.js:1:28175)
    at N (/usr/src/fe/node_modules/terser/dist/bundle.min.js:1:38279)
    at /usr/src/fe/node_modules/terser/dist/bundle.min.js:1:30375
    at /usr/src/fe/node_modules/terser/dist/bundle.min.js:1:28763
    at /usr/src/fe/node_modules/terser/dist/bundle.min.js:1:32107
    at /usr/src/fe/node_modules/terser/dist/bundle.min.js:1:32217
    at /usr/src/fe/node_modules/terser/dist/bundle.min.js:1:28763
  - code: [undefined]
  - codeFrame: Unexpected token: eof (undefined)
  - errorMessage: Unexpected token: eof (undefined)
        at UglifyWriter
-~- created here: -~-
    at UglifyWriter.Plugin (/usr/src/fe/node_modules/broccoli-plugin/index.js:7:31)
    at new UglifyWriter (/usr/src/fe/node_modules/broccoli-uglify-sourcemap/index.js:38:10)
    at UglifyWriter (/usr/src/fe/node_modules/broccoli-uglify-sourcemap/index.js:33:12)
    at Class.postprocessTree (/usr/src/fe/node_modules/ember-cli-uglify/index.js:54:50)
    at projectOrAddon.addons.reduce (/usr/src/fe/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/usr/src/fe/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/usr/src/fe/node_modules/ember-cli/lib/broccoli/ember-app.js:866:12)
    at EmberApp.host.addonPostprocessTree (/usr/src/fe/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/usr/src/fe/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
```

**Comment by andygoalkeeper** [comment] 2020-05-02 11:33
It may be related to release of moment.js 2.25.
Try to downgrade (add `"moment": "2.24.0"` in `package.json`).

https://github.com/moment/moment/issues/5481

**Comment by fabiosantoscode** [comment] 2020-05-02 15:27
Two things @devdemi:

 - Can you enable npmjs.com/source-map-support such that the stack traces are prettier?
 - Could you try updating moment to 2.25.1?

**Comment by erikap** [comment] 2020-05-02 17:18
I still get the same error using moment 2.25.1. Rollback moment to v2.24.0, as suggested by @andygoalkeeper, seems to work :+1:

**Comment by fabiosantoscode** [comment] 2020-05-02 19:32
I believe this should be fixed at the moment level if reverting to 2.24.0 fixes it! I see a bunch of people pitching in on issues there, so I have hope that this problem is fixed eventually.

The error message is very interesting though. It's as if the file ends without closing a function or parens. Can anyone reproduce this same error message with another bundler such as webpack or rollup?

**Comment by tdukai** [comment] 2020-05-08 07:43
Rolling back moment package DOES NOT HELP!

**Comment by jrjohnson** [comment] 2020-05-08 19:08
I'm not able to determine where in Moment this error is originating. Anyone have tips on enabling some debugging to get an idea about where to start looking?

**Comment by andygoalkeeper** [comment] 2020-05-08 19:19
@jrjohnson 

```
npm install -g ember-cli
ember new project
cd project
ember install ember-moment
ember build --environment=production
```

https://github.com/ember-cli/ember-cli/issues/9206.
It's still actual for latest npm-package `moment 2.25.3` (dependency for `ember-moment`).

**Comment by fabiosantoscode** [comment] 2020-05-09 14:05
To ensure a revert:

If you're using yarn you can do as [was mentioned here](https://github.com/stefanpenner/ember-moment/issues/328#issuecomment-625656801).

With npm, you can `npm ls moment` which shows every version of moment you might have deep in your dependency tree.

**Comment by fabiosantoscode** [comment] 2020-05-09 14:09
@jrjohnson

What is the bundler? 

I've been thinking of enabling some options to help debugging in the future, such as "snitching" what was the input code by placing it in some files, since 99% of terser users use it through a bundler, or making terser "pass-through", since it might be easier to change Terser options than to disable.

Something you can do for now, is to try and disable Terser entirely and look at the output. Is it valid javascript that you can run in your browser? If it is, that's a Terser bug. Except for `?.` and `??` which aren't supported yet.

**Comment by jrjohnson** [comment] 2020-05-09 16:57
Thanks @fabiosantoscode feels like I should have thought of that! The bundler is Broccoli and ember-cli, turning off minification there does produce invalid JS so this issue is not with terser. Now that I have some output to work with I'll start looking for the issue in there.

**Comment by fabiosantoscode** [comment] 2020-05-09 17:09
Great, I'll be closing this then! Thanks!

**Closed by fabiosantoscode** 2020-05-09 17:09 UTC

**Comment by jrjohnson** [comment] 2020-05-11 04:35
This should be fixed for ember apps with the release of `ember-moment-shim` `v3.8.0` which no longer double minifies code from moment.

**Comment by fabiosantoscode** [comment] 2020-05-11 13:43
What's going on? Double minifying is inefficient but it's certainly possible. It's not like Terser is unable to parse its own output.

**Comment by brianhjelle** [comment] 2020-05-12 00:23
Bumbing ```ember-moment-shim``` to ```v3.8.0``` fixed it for me. Thanks.

**Comment by jrjohnson** [comment] 2020-05-18 15:22
@fabiosantoscode I don't think moment is minifying with terser internally, but I also don't think the issue is actually the minification itself as I can run `terser min/moment.min.js -c sequences=30  -m safari10=true` just fine against the minified moment source. I think the problem is in moment now including ES module imports. It's likely ember is going some transformation when it sees those, but it doesn't see them in minified code.
