### ISSUE TITLE
Significant performance degradation over time since 4.2.0

### ISSUE THREAD

**Issue by lukeapage** [terser/terser#473] opened 2019-09-29 19:59 UTC
**Bug report or Feature request?**

Bug ??

**Complete CLI command or `minify()` options used**

```
                terserOptions: {
                    ecma: 5,
                    mangle: true,
                    compress: {
                        defaults: false,
                        dead_code: false,
                        side_effects: false,
                        unused: false,
                    },
                },
```

source maps are off, extract comments are off.

I'm running inside webpack via the terser-webpack-plugin but I can have a go at narrowing it down with a direct cli run if that will help.

**Details**

It appears that the time it takes terser to run has increased significantly for us, when only getting rid of whitespace and mangling.

version time  minified size
4.1.4 - 134s, 25,704kb
4.2.0 - 304s, 25,703kb
4.2.1 - 295s, 25,703kb
4.3.0 - 453s, 25,735kb
4.3.4 - 442s, 25,735kb

Note these are timings with webpack and babel and caches cleared, so the timing increase in terser itself is way more than 3x

Do you have any idea why? I am really not sure I can fix this, but if I work out the commits causing the problem, would it help or do you have an idea why already?

**Comment by fabiosantoscode** [comment] 2019-09-29 20:03
In this case, if the repository is publicly available you can just send a link to it and I'll give it a go. 

It's not necessary to get a reproduction with Terser alone in this case specifically, because a regression can (at least at first) be investigated using git bisect.

**Comment by fabiosantoscode** [comment] 2019-09-29 20:05
I've heard of this issue but nobody's been able to supply me with a reproduction, and I can't reproduce it myself.

**Comment by lukeapage** [comment] 2019-09-29 20:13
It’s not public - it’s a very large private web app. I guess I need to work out a repro with something that is public..

**Comment by fabiosantoscode** [comment] 2019-09-29 20:44
I haven't had any luck with that :/

**Comment by lukeapage** [comment] 2019-09-30 07:09
I tried react, lodash and a large json file and didn't get any regression. I used our app to do a git bisect.

https://github.com/terser/terser/commit/2cf4041e3daf347e8fc61f168bb4258b6c447c32
before: 24 seconds
after: 38 seconds

Looking at the PR, its pretty terser specific so I have a hard time understanding it.
I am testing with minifying the already minified file which only has ~20 license comments in it and the regression still exists - so I am not sure what could cause it. Does that help?
I'll have a go at narrowing down the next regression.

**Comment by lukeapage** [comment] 2019-09-30 07:28
This is the second regression: 

803c703429ecd7d0f20c87159fa471de4a951669

before: 38 seconds
after: 2 minutes 18 seconds

**Comment by lukeapage** [comment] 2019-09-30 07:29
Thats a bigger change, but interestingly uses alot of WeakSets and WeakMaps - concidence?

**Comment by lukeapage** [comment] 2019-09-30 09:00
I was on node v10.15
I upgraded to v12.11
before: 3m45
after 3m58

Found the 3rd regression:

2228a8e85e284ba867686341b63a34d87b638739

before: 2m23
after: 3m40

**Comment by fabiosantoscode** [comment] 2019-09-30 14:00
Goodness gracious.

It looks like I made some terrible assumptions about the performance impact of using WeakMaps and WeakSets.

I'll be looking into this, thanks.

Just to dispel concerns of a GC related issue, can you please check if the current version uses more memory than 4.1.3?

**Comment by kzc** [comment] 2019-09-30 16:24
The 3rd regression is easily remedied by reverting [this line](https://github.com/terser/terser/commit/cfc475528c81101be99ebee5eec0ca435a386e84#diff-00fe37b20ddfb9ecc9c492b0725fa2b2L171-R171). Outputting comments should only be an opt in. This default change would be surprising to most long time uglify users.

The "some" comments [regex addition](https://github.com/terser/terser/commit/cfc475528c81101be99ebee5eec0ca435a386e84#diff-00fe37b20ddfb9ecc9c492b0725fa2b2R161) of `|^\**!` should be limited to a few characters rather than being boundless.

The comments de-duplication code introduced in the [1st regression](https://github.com/terser/terser/commit/2cf4041e3daf347e8fc61f168bb4258b6c447c32) appears to execute whether or not comments output is enabled. That point aside, I don't think a Set should be required (weak or otherwise) to de-duplicate consecutive comments in issue #396 - it's an artifact of various AST nodes pointing to the same comment and should be fixed in another way.

**Comment by lukeapage** [comment] 2019-09-30 16:37
I’ve been trying to reproduce the problems with a public file, including a build that’s a subset of the one causing a problem.. and I cannot. It makes me suspect the degradation is only affecting very large files.
Could it be that WeakSet causes performance issues when v8 is trying very hard to free memory?

**Comment by kzc** [comment] 2019-09-30 17:38
It's largely a function of code size. Map and Set lookups have O(log n) complexity. In the case where AST node properties were replaced with containers, the `n` can get very large, whereas in the previous code the object properties were a small fixed number.

**Comment by fabiosantoscode** [comment] 2019-09-30 18:03
I've managed to reproduce the issue on a payload which is basically `(function(){ ${ entireTerserJsBundle } }())` thirty times. For this enormous payload the compress time was increased around 2x.

I've read @kzc's comment and am now trying to change the code such that is uses a bitfield instead of several WeakSets, and will try and remove Maps and Sets from the codebase.

**Comment by fabiosantoscode** [comment] 2019-09-30 18:22
I got some gains from doing this, but not as many as I expected.

**Comment by lukeapage** [comment] 2019-09-30 18:46
I did a search and replace of WeakMap/WeakSet to Map/Set and then re-ran my tests - all of the regressions disappeared and it went to 28 seconds again on master.

**Comment by fabiosantoscode** [comment] 2019-09-30 19:42
Oh yes, that worked here too :) Actually with the bitfield instead of any sets etc there was a speed gain over the old stuff!

**Closed** 2019-10-01 12:31 UTC

**Comment by fabiosantoscode** [comment] 2019-10-06 16:45
Thanks @kzc I was looking for something like that but couldn't find anything.
