### ISSUE TITLE
[Bug?] Terser suppresses module exports

### ISSUE THREAD

**Issue by benallfree** [terser/terser#668] opened 2020-04-26 06:44 UTC
I have an un-tersed webpack bundle. It's iife and if i paste it in the console, I get 

`Module {default: {…}, __esModule: true, Symbol(Symbol.toStringTag): "Module"}`

But when I paste the terser'd version, I just get `undefined`

How do I get terser to return the same thing as the original version? It seems like a bug that the output from the terser version is not the same as the output from the original.

**Comment by jridgewell** [comment] 2021-09-07 04:04
I'm closing this as not reproducible, since we don't have an input code to debug. If you can respond with an input and the options you're passing to terser, we can reopen.

**Closed by jridgewell** 2021-09-07 04:04 UTC
