### ISSUE TITLE
Unexpected token: punc ({) after Typescript 4.5.5 -> 4.6.0 upgrade

### ISSUE THREAD

**Issue by 2-5** [terser/terser#1160] opened 2022-03-02 21:28 UTC
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
5.12.0

**Complete CLI command or `minify()` options used**
default options

**`terser` input**

Code generated by `Typescript 4.6.0`
No errors if code is generated by `Typescript 4.5.5`

```javascript
class Exchange extends vuex_orm_esm.Model {
    static { this.entity = "exchanges"; }  // <----------- error reported at first { character on this line
    static { this.primaryKey = "id"; }
    static fields() {
        return {
            id: Exchange.string(null),
            name: Exchange.string(""),
        };
    }
}
```

The error seems to
**`terser` output or error**

```
ERROR in main.js
main.js from Terser plugin
Unexpected token: punc ({) [main.js:2,11]
    at js_error (\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (\node_modules\terser\dist\bundle.min.js:1288:9)
    at as_property_name (\node_modules\terser\dist\bundle.min.js:3076:20)
    at concise_method_or_getset (\node_modules\terser\dist\bundle.min.js:2729:20)
    at class_ (\node_modules\terser\dist\bundle.min.js:2685:22)
    at statement (\node_modules\terser\dist\bundle.min.js:1462:24)
    at _embed_tokens_wrapper (\node_modules\terser\dist\bundle.min.js:1339:26)
    at block_ (\node_modules\terser\dist\bundle.min.js:2172:20)
```

**Expected result**

**Comment by Conduitry** [comment] 2022-03-02 21:45
This sounds like a duplicate of #1093.

**Comment by jridgewell** [comment] 2022-03-02 21:58
Yup, we don't yet support class static blocks.

**Closed by jridgewell** 2022-03-02 21:58 UTC
