### ISSUE TITLE
Resolve Switch Statements with Static Conditions

### ISSUE THREAD

**Issue by Lakuna** [terser/terser#1482] opened 2023-12-18 01:43 UTC
**Bug report or Feature request?**

Feature request.

**Version (complete output of `terser -V` or specific git commit)**

```powershell
terser 5.26.0
```

**Complete CLI command or `minify()` options used**

```powershell
terser ./test.js --compress --module
```

**`terser` input**

```javascript
function isOneOrTwo(a) {
	switch (a) {
		case 1:
			return "one";
		case 2:
			return "two";
		default:
			return "not one or two";
	}
}

console.log(isOneOrTwo(1));
```

**`terser` output or error**

```javascript
console.log(function(a){switch(a){case 1:return"one";case 2:return"two";default:return"not one or two"}}(1));
```

**Expected result**

```javascript
console.log("one");
```

**Comment by Lakuna** [comment] 2023-12-18 01:43
Note that running the same command on the actual output produces the expected output, so it seems that this can probably be implemented by just reordering some optimizations.

**Comment by fabiosantoscode** [comment] 2023-12-19 15:11
This is a duplicate of #1481 in a way. Pulling in a function and then optimizing it can be achieved by incrementing the `passes` option.

**Closed by fabiosantoscode** 2023-12-19 15:11 UTC
