### ISSUE TITLE
Compress property access using constants

### ISSUE THREAD

**Issue by sirian** [terser/terser#935] opened 2021-02-16 19:29 UTC
**Feature request**

Could not find an option to compress constant property access. This could allow significantly reduce size after minification.

**`terser` input**

```javascript
console.log(A.constructor.name, B.constructor.name, C.constructor.name, D.constructor.name)
```

**`terser` output**
```javascript
console.log(A.constructor.name, B.constructor.name, C.constructor.name, D.constructor.name)
```

**Expected result**
```javascript
const c = 'constructor', n = 'name';
console.log(A[c][n], B[c][n], C[c][n], D[c][n])
```

Just look at example from real project (this is only a part of code generated by TypeScript decorators)
![image](https://user-images.githubusercontent.com/897643/108109475-f9a0a600-70a2-11eb-9b2e-a2722f8311bb.png)

`2610 bytes` vs `2183 bytes`

Example 2:
https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js

`.length` occurs 232 times
`.prototype` occurs 78 times
`.push` occurs 37 times
`.replace` occurs 24 times
etc..

Example 3:

https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js
`.length`  - 164 times
`.nodeType` - 83 times
`.parentNode` - 54 times
`.toLowerCase` - 46 times
`.createElement`  - 24  times
etc...

**PS - Of course this could be unsafe in some cases**
For example this works
```javascript
(() => {
    const foo = () => window.open('');
    setTimeout('(' + foo  + ')()', 1000);
})();
```

but this - doesn't
```javascript
(() => {
    const o = 'open';
    const foo = () => window[o]('');
    setTimeout('(' + foo  + ')()', 1000);
})();
```

**Comment by fabiosantoscode** [comment] 2021-03-02 20:26
Hey there!

This is an old discussion, a duplicate of #590.

There are some performance concerns to doing this, which may or may not be legitimate.

**Closed by fabiosantoscode** 2021-03-02 20:26 UTC
