### ISSUE TITLE
Do not inline constants in multiple places when that will cause a size increase.

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [terser/terser#790] opened 2020-08-17 10:35 UTC
**Feature request?**
There are situation where inlining actually doesn't bring profits in smaller size and actually makes code even bigger than originally written. See example below. Inlining makes sense only if length of given string and its declaration keywords is bigger then total length of all appearances of given string. Same goes with numbers.

**`terser` input**

```javascript
const _string_ = "string";

alert(_string_);
alert(_string_);
alert(_string_);
alert(_string_);
```

**`terser` output**
```javascript
alert("string");
alert("string");
alert("string");
alert("string");
```

**Expected result**
```javascript
const a = "string";
alert(a);
alert(a);
alert(a);
alert(a);
```

**Comment by fabiosantoscode** [comment] 2020-08-18 00:29
This is an old, known issue. I can't find the old issue to link it here though.

It can be fixed by letting the size calculation part of Terser know about whether you've turned on mangling. Right now it assumes that `_string_` is going to be 8 characters long, which is obviously not the case after a mangling pass.

I'm having a go at this right now, and I partially fixed it (IE it's fixed for the `inline` option) but it's not fixed for `evaluate` which is going to go ahead and turn every symbol there into its calculated value without considering duplication.

**Comment by DanielMazurkiewicz** [comment] 2020-08-18 08:13
> but it's not fixed for `evaluate` which is going to go ahead and turn every symbol there into its calculated value without considering duplication.

It's a bit more complicated case, but also should be considered when inlining calculated values and even calculating values:

*input:*
```javascript
const $read$ = "read";
const $only$ = "only";
const $readonly$ = $read$ + $only$;

pass($read$);
pass($only$);
pass($readonly$);
```
*expected result*
```javascript
const a = "read", b = "only", c = a+b;

pass(a);
pass(b);
pass(c);
```

**Comment by DanielMazurkiewicz** [comment] 2020-08-18 08:45
While thinking of that issue, I got an idea that it would be actually probably easier to let inline and calculate everything and then add a stage that would collect all of numbers and strings and add a sort of smart dictionary at the beginning of code

*input:*
```javascript
const $read$ = "read";
const $only$ = "only";
const $readonly$ = $read$ + $only$;

pass($read$);
pass($read$);
pass($only$);
pass($only$);
pass($readonly$);
pass($readonly$);
```

*inlined and precalculated:*
```javascript

pass("read");
pass("read");
pass("only");
pass("only");
pass("readonly");
pass("readonly");

```

*result of new stage:*
```javascript
// automatically prepared dictionary based on previous stage
const a = "read", b = "only", c = a+b;
// end of dictionary

pass(a);
pass(a);
pass(b);
pass(b);
pass(c);
pass(c);
```

What do you think @fabiosantoscode ?

**Comment by danieltroger** [comment] 2021-04-18 09:44
Just wanted to chime in that I also noticed this and was about to open an issue.

For some reason terser inlines variables with long variable names - which parcel 2's scope hoisting produces - even if it is longer than renaming the variables to a,b,c etc and keeping them

**Comment by danieltroger** [comment] 2021-04-18 09:46
I saw this was merged https://github.com/terser/terser/pull/661 but it doesn't seem to have fixed it?

Here's what I wanted to post to reproduce, enter this into https://try.terser.org/:

```
const $c426863bb391d48c0e057e38c916800f$var$car_sel = "this is a long string ";
console.log($c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel + ", " + $c426863bb391d48c0e057e38c916800f$var$car_sel);
```

**Comment by arthurfiorette** [comment] 2022-04-07 18:46
Any updates on this issue?

**Comment by fabiosantoscode** [comment] 2022-04-08 10:07
Not really.

There are good repros in this thread but I'm not sure it's an easy fix. This isn't caused by the `inline` option anymore though.

**Comment by fabiosantoscode** [comment] 2022-04-08 11:05
Actually it *is* an easy fix because it's always strings. So if the typeof the evaluated *thing* is a string, it can be measured against the original expression.

**Comment by fabiosantoscode** [comment] 2022-04-08 11:06
Will check this out later today

**Comment by fabiosantoscode** [comment] 2022-04-09 12:45
There was a bug hanging out near the fix for this so I can't merge the simple fix right away.

**Closed** 2022-11-24 17:30 UTC
Labels: suboptimal-output
