### ISSUE TITLE
Terser removes JSDoc comments even with @preserve or @license

### ISSUE THREAD

**Issue by Bauke** [terser/terser#223] opened 2019-01-03 13:33 UTC
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V`)**

`terser 3.14.0`

**Complete CLI command or `minify()` options used**

CLI

`npx terser src/index.js -o dist/index.js` (didn't install globally)

`src/index.js`:

```javascript
/**
 * @function main
 * @param {string} test String test parameter
 * @license MIT
 */
function main(test) {
  console.log(test);
}

main('Hello');
```

`dist/index.js`:

```javascript
function main(test){console.log(test)}main("Hello");
```

**Expected result**

According to the docs in the README: `By default [...], keeping JSDoc-style comments that contain "@license" or "@preserve".` So it should keep the comments by default but it isn't.

I searched around and there's no other issues surrounding JSDoc here so maybe I'm just using it incorrectly?

**Comment by sunpietro** [comment] 2019-08-07 09:24
Has it been solved already?

**Comment by zhaparoff** [comment] 2019-09-14 08:49
The same thing. `v4.3.1`

**Comment by zhaparoff** [comment] 2019-09-14 09:47
One detail, probably not very clear from the docs.
By default, if no `comments` flag was specified, tool eliminates all the comments.
To make it leave some, as defined in the docs, you should pass `comments=some`
https://github.com/terser/terser/blob/master/lib/output.js#L196-L220

Anyway, even considering this, this not working as intended for me.
Even if I'm specifying `comments = all`, the tool eliminates the JSDoc comment in the begginnig of the file, although all other one-line comments remain untouched.

**Comment by fabiosantoscode** [comment] 2019-09-25 15:35
@zhaparoff that's some serious bug. I can't reproduce this though. Could you please open an issue for this?

On another note, I plan to change Terser such that the default `comments` option outputs license information.

**Comment by fabiosantoscode** [comment] 2019-09-25 15:36
Here's my attempt to reproduce:

bug.js:
```
/**                                             
 * @function main                               
 * @param {string} test String test parameter   
 * @license MIT                                 
 */                                             
function main(test) {                           
  console.log(test);                            
}                                               
                                                
main('Hello');                                  

```

```
fabio@fabio-thinkpad ♥  cat bug.js | bin/terser --comments all --toplevel -mc
/**
 * @function main
 * @param {string} test String test parameter
 * @license MIT
 */
var l;l="Hello",console.log(l);
```

**Comment by zhaparoff** [comment] 2019-09-26 07:51
@fabiosantoscode indeed, I can't reproduce it, when using the terser itself.
But it is reproducible when using _rollup_ and _rollup-plugin-terser_.
Although, I can see any major difference in the plugin, which simply passes user defined options to `terser.minify()` call. 
Again, it works fine for a simple code like your example.
But not for my project with css and images embedded into the js, as a long string variable:

```
var Alert = (function () {
    'use strict';

    var css = "<Styles definition with base64 encoded images, containing over 68k symbols>";

    /**
     * @license CDDL
     * Copyright 2019 - Anton Zhaparov
     */

    var AlertStatic = /** @class */ (function () {
          // Some function where css string is used
          AlertStatic.prototype.show = function (title, message, icon, buttons, width, height, padding, preventCancel) {
            var _this = this;
            this.isInitialised = false;
            ...
          }
...
```

For some reason css variable is not inlined, when using terser iself, but is inlined, eliminating the following license comment, when using rollup plugin.
So most likely, this is a plugin issue, and not a terser one.

**Comment by fabiosantoscode** [comment] 2019-09-26 12:30
> So, most likely, this is a plugin issue, and not a terser one.

I'm not aware of rollup-plugin-terser touching the code at all besides telling Terser to do its thing. Am I wrong @TrySound?

This might be a different Terser version that the plugin is using, or some option that it adds by default.

**Comment by TrySound** [comment] 2019-09-26 12:41
The plugin only maintain `module` and `sourceMap` options. @zhaparoff Try to remove and install again terser plugin to update transitive dependencies.

**Comment by ar-rm** [comment] 2020-05-24 07:10
I think I ran into this and I *might* have found the conflict and have a workaround.

### Issue:

As @zhaparoff found, TerserJS + [RollupJS](https://github.com/rollup/rollup) = Loud comments are *removed* when they shouldn't be.



```
/!*
Loud comment, via `!`, should remain but is removed
*/

/*
@preserve Should remain but is removed
@license Should remain but is remove
*/

```

#### From the Docs:

> "comments (default "some") -- by default it keeps JSDoc-style comments that contain "@license" or "@preserve", pass true or "all" to preserve all comments, false to omit comments in the output, a regular expression string (e.g. /^!/) or a function."
>
> https://github.com/terser/terser#output-options


------


### Workaround (for me):

I found a TerserJS option that seems to fix this **and retains the loud comments**:

- "Keep All Function Names"
- `keep-fnames=true` (default: `false`)


#### From the Docs:

> "keep_fnames (default: false) - pass true to prevent discarding or mangling of function names. Pass a regular expression to only keep class names matching that regex. Useful for code relying on Function.prototype.name. If the top level minify option keep_classnames is undefined it will be overridden with the value of the top level minify option keep_fnames."
> 
> https://github.com/terser/terser#minify-options

The trade-off is the lack of shortened function names (since that's what the option does).

IOW: There's something about the way TerserJS shortens/mangles function names as a result of something else with RollupJS. Sorry, I can't say something more specific than "something" ;-)

FYI:
- I tried commenting out ALL `import` statements (effectively disabling RollupJS) and setting TerserJS to `keep-fnames=true` and `keep-fnames=false`.
- **Result:** ✅ Comments were *retained*.
- I think that helps to isolate/confirm a conflict between TerserJS and RollupJS.

------


I'm using [CodeKit](https://codekitapp.com) (3.12.1), which is essentially a UI equivalent to Webpack for Macs.

It's using:
- TerserJS: [4.6.11](https://github.com/terser/terser/releases/tag/v4.6.11) *Currently @ 4.7.0*
- RollupJS: [2.7.1](https://github.com/rollup/rollup/releases/tag/v2.7.1) *Currently @ 2.10.9*

#### re: `comments=some`

I don't seem to be able to set that in CK. Only `true` and `false`. But I'm also not sure of its default (i.e.: It's possible that `some` is what CK uses for its `false` state). But according to what @zhaparoff wrote above, this probably doesn't make a difference.


But I don't think CK is getting in the way. At worst, it's using an old versions of TerserJS and RollupJS. But if anyone thinks it has to do with CK, that would be good to know too. I can submit a bug to the developer. He's very responsive.


------


Can anyone else confirm with your examples above?

If not, I'll try to put together a reduced test case.

I hope this helps.

Thanks!

**Comment by fabiosantoscode** [comment] 2020-05-27 14:36
Thanks for all the research!

I was able to create a minimum reproducible sample of code from this thread. The confounding variable here is the wrapping function. Rollup might be creating one depending on your options (Terser's compilation step involves Rollup, which does create a wrapping function).

```
(() => {                                      
    const Alert = (() => {                        
        /* @preserve */
        var IWillBeMovedAndRuinTheComment = leak()
        leak(IWillBeMovedAndRuinTheComment)       
    })()                                          
                                                  
    leak(Alert)                                   
})()                                                
```

If you remove the outer wrapping function, `@preserve` is no longer preserved. The reason is that, when the `toplevel` option is absent and you're in the toplevel scope, Terser is reluctant to inline, because sometimes it needs to add new `var` which at the toplevel, infects the `window` object in a browser.

Disabling the `inline` variable fixes this.

**Comment by ar-rm** [comment] 2020-05-29 04:32
Thanks for the information @fabiosantoscode

I tried your code at https://try.terser.org/ and see what you mean.

- Those two additional options `toplevel` and `inline` seem interesting as well.
- I was going to try to test on my code but then...


I stopped being able to exactly reproduce the original issue. I found some other interesting behaviors (more below), but even after going back a few commits, the comments remain! As if there was no bug. What that!?

I'm not exactly sure what happened. I'm really sorry. I'll keep trying.


Here are the other things I noticed:


------------


1. Comments placed at the **very top** of the file are moved **below** the IIFE that Rollup creates.

    - But apparently that's either intentional or a known issue, or something else :-)
    - Because this exists: https://github.com/jacksonrayhamilton/rollup-plugin-shift-header
    - IOW: So be it.


However only ONE comment will be retained **if** the comments are **above** the `import` statements:

This:
```
/*! Loud comment 1*/
/*! Loud comment 2*/

import * as utils from './path/file.js';
```

Reduces to this:
```
`!function(){"use strict";...`   <-- the IIFE

/*! Loud comment 1*/
```

❌ Not expected


2. However if the `import` statements are moved to the **very top** of the file, **both** loud comments (and any others) are retained!

    - ✅ As expected
    - IOW: Loud comments made **above** `import` statements have unexpected results.
    - I see the pattern, but there's either a reason I don't know, or it's a bug.
    - Weird!


------------

@fabiosantoscode:
> Terser's compilation step involves Rollup, which does create a wrapping function

Maybe you already realize this, but:

Could it be that there's a conflict between the Rollup functions that run as a **part of TerserJS** and Rollup that's run **independently** at a later (or earlier) stage in the build process?

And our guess-and-check method of enabling/disabling options (ex: ["Compression" options](https://terser.org/docs/api-reference#compress-options) ) is exposing these?


-------------


#### FYI:

This is what I see in CodeKit.

Out of view (at the bottom) are the ["Compression" options](https://terser.org/docs/api-reference#compress-options): `Arguments` through `Wrap_life`

A little more information about CodeKit and TerserJS:
https://codekitapp.com/help/terser/

![Screen Shot 2020-05-28 at 5-28, 11 51 37PM](https://user-images.githubusercontent.com/199155/83221422-c64c6e80-a143-11ea-8e23-ec350a356a95.png)

**Comment by fabiosantoscode** [comment] 2020-05-29 21:57
I used to assume it was different, but it seems like what rollup does is basically

terser.minify(bundleAllModules())

So, rollup has already done its transformations when the code reaches Terser. This is part of the reason there aren't many cross module optimisations that Terser can do. Terser doesn't get to see any imports :)

**Comment by raphaelokon** [comment] 2021-01-26 16:49
Did anyone solve this?

**Comment by fabiosantoscode** [comment] 2021-01-26 20:30
Version 3 used to default the comments option to false. Check out the readme here:

https://github.com/terser/terser/tree/v3.17.0

The current version does preserve some comments by default.

I'm closing this because apparently it's about an older Terser version, which has the option to accept more comments.

**Closed by fabiosantoscode** 2021-01-26 20:30 UTC
