### ISSUE TITLE
Terser output changes depending on variable name, sometimes creating inefficient code

### ISSUE THREAD

**Issue by Zlatkovsky** [terser/terser#1289] opened 2022-11-03 05:35 UTC
**Bug report**

**Version 5.15.1**

**terser --compress --mangle -- code.js**

**`terser` input**
```
export function doSomething() {
	const propName = "aVeryLongAndRidiculouslyVerboseProperty";

	if (!window[propName]) {
		window[propName] = Math.random();
	}
	console.log(window[propName]);
};
```

For the code above, Terser outputs what I would expect: it replaces `propName` with a single-character variable `o`, as well as does does a couple other small optimizations (replacing `if` statement with `||`, and does minor syntactic adjustments):

**Output 1, as expected (140 bytes)**
```
export function doSomething(){const o="aVeryLongAndRidiculouslyVerboseProperty";window[o]||(window[o]=Math.random()),console.log(window[o])}
```

But here is the weird thing. Suppose I rename `propName` to something else, e.g., start appending the letter `e` at the end.

For a while, the output stays the same, even for `propNameeeeeeeeeeee`.

But add another couple dozen `e`s, making it `propNameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`, and suddenly the output changes! Instead of keeping the const and continuing to output it as a single-character variable, Terser decides to start inlining the value of the property value: which results in far more bytes!

**Input 2:**
```
export function doSomething() {
	const propNameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = "aVeryLongAndRidiculouslyVerboseProperty";

	if (!window[propNameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee]) {
		window[propNameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee] = Math.random();
	}
	console.log(window[propNameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee]);
};
```

**Output 2: (201 bytes)**
```
export function doSomething(){window.aVeryLongAndRidiculouslyVerboseProperty||(window.aVeryLongAndRidiculouslyVerboseProperty=Math.random()),console.log(window.aVeryLongAndRidiculouslyVerboseProperty)}
```

**Expected result**

I would expect `Output 2` to be identical to the original output (and be 140 bytes instead of bloating to 201)

**Comment by fabiosantoscode** [comment] 2022-11-13 09:10
Appreciate the report! This in particular is a problem with the `properties` option.

**Comment by fabiosantoscode** [comment] 2022-11-24 10:51
I've found that this is actually a duplicate of https://github.com/terser/terser/issues/790

**Closed by fabiosantoscode** 2022-11-24 10:51 UTC
Labels: suboptimal-output
