### ISSUE TITLE
Two classes assigned to same variable in 4.3.5

### ISSUE THREAD

**Issue by JonWallsten** [terser/terser#486] opened 2019-10-07 12:21 UTC
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 4.3.5 (works in 4.3.4)

**Complete CLI command or `minify()` options used**
```
{
    ecma: 5,
    keep_classnames: true,
    keep_fnames: true,
    // Temporary fix for this bug:
    // https://github.com/angular/angular/issues/31595
    compress: {
        global_defs: GLOBAL_DEFS_FOR_TERSER
    }
}
```

**`terser` input**
```
class TimeHelper {
    private timers = {};

    public time (label: string): string {
        if (!label || label === '') {
            label = 'default';
        }
        this.timers[label] = Date.now();
        return 'timeStart-' + label + ': ' + new Date(this.timers[label]).toISOString();
    }

    public timeEnd (label: string): string {
        if (!label || label === '') {
            label = 'default';
        }
        const timerStop = Date.now();
        const elapsed = timerStop - this.timers[label];
        delete this.timers[label];
        return 'timeEnd-' + label + ': ' + new Date(timerStop).toISOString() + ' elapsed time (ms): ' + elapsed.toString();
    }
}

/**
 * Helper class to create and hold a log writer
 */
class LogWriter {
    public constructor (writers: Array<IOasLogApiWriter>) {
        const that = this;
        that.writer = {} as IOasLogApiWriter;

        logFunctions.forEach(function (funcName) {
            // Set the new writer if it is specified
            writers.forEach(function (writer) {
                if (writer && !that.writer[funcName] && writer[funcName]) {
                    // Bind with correct this for later invocation
                    that.writer[funcName] = writer[funcName].bind(writer);
                }
            });
            if (!that.writer[funcName]) {
                that.writer[funcName] = OasLogger.nop.bind(undefined);
            }
        });
        // Hook up the buffer writer functions if they exist
        bufferFunctions.forEach(function (funcName) {
            writers.forEach(function (writer) {
                if (writer && !that.writer[funcName] && writer[funcName]) {
                    that.writer[funcName] = writer[funcName].bind(writer);
                }
            });
        });
    }

    public writer;
}
```
**`terser` output or error**
```
var y = function() {
    function e() {
        this.timers = {}
    }
    return e.prototype.time = function(e) {
        return e && "" !== e || (e = "default"),
        this.timers[e] = Date.now(),
        "timeStart-" + e + ": " + new Date(this.timers[e]).toISOString()
    }
    ,
    e.prototype.timeEnd = function(e) {
        e && "" !== e || (e = "default");
        var t = Date.now()
            , n = t - this.timers[e];
        return delete this.timers[e],
        "timeEnd-" + e + ": " + new Date(t).toISOString() + " elapsed time (ms): " + n.toString()
    }
    ,
    e
}()
    , y = function(e) {
    var t = this;
    t.writer = {},
    p.forEach((function(n) {
        e.forEach((function(e) {
            e && !t.writer[n] && e[n] && (t.writer[n] = e[n].bind(e))
        }
        )),
        t.writer[n] || (t.writer[n] = h.nop.bind(void 0))
    }
    )),
    f.forEach((function(n) {
        e.forEach((function(e) {
            e && !t.writer[n] && e[n] && (t.writer[n] = e[n].bind(e))
        }
        ))
    }
    ))
}
```

**Expected result**
I expect the two classes to keep their class names intact based on the options I pass. Even if they don't they shouldn't be assigned to the same letter, `y`. In 4.3.4 they get assigned to `y` and `b`

**Comment by herberttn** [comment] 2019-10-07 16:49
Hello!

Same problem here. For some reason an already existing token is being assigned to a function argument, and in the case below we're getting an `Uncaught TypeError: e is not a function`.

`e` is an external function (for this function's context), and when `e` is assigned to the argument, the function call loses the reference it wants to call.

Original code:
```javascript
function a(a) {
  var d = e(this);
  return d[a] || (d[a] = new b(a))
}
```
v4.3.4 output (working):
```javascript
function a(n) {
  var r = e(this);
  return r[n] || (r[n] = new t(n))
}
```
v4.3.5+ output (breaking):
```javascript
function a(e) {
  var t = e(this);
  return t[e] || (t[e] = new b(e))
}
```

**Comment by newsiberian** [comment] 2019-10-08 03:56
Hi, the same here with:
```js
{
  mangle: true,
  keep_classnames: true,
  keep_fnames: true,
}
```

**Comment by JonWallsten** [comment] 2019-10-08 04:22
@herberttn: You don't actually have to fork the terser-webback-plugin. If you add terser@4.3.4 to your apps package.json it will be used by terser-webpack-plugin. That's at least how we solved it.

**Comment by herberttn** [comment] 2019-10-08 12:32
> @herberttn: You don't actually have to fork the terser-webback-plugin. If you add terser@4.3.4 to your app's package.json it will be used by terser-webpack-plugin. That's at least how we solved it.

Yes we know, we just wanted to keep things separate ;)
But thanks anyway @JonWallsten!
I'm someone will find the tip really useful until this is solved.

**Comment by kopax** [comment] 2019-10-10 21:15
> @herberttn: You don't actually have to fork the terser-webback-plugin. If you add terser@4.3.4 to your app's package.json it will be used by terser-webpack-plugin. That's at least how we solved it.

I can't do that since I have a lot of packages to update then. I am waiting for a fix or a revert. All our documentations are broken (See #490)

**Comment by fabiosantoscode** [comment] 2019-10-13 15:44
Please provide a JS example. It might be useful to see what typescript generated it but it's not a very useful example since it's not valid Terser input.

**Comment by fabiosantoscode** [comment] 2019-10-13 15:58
@herberttn I can't reproduce with your example:

```
fabio@fabio-thinkpad ♥  cat bug.js 
    function a(a) {
      var d = e(this);
      return d[a] || (d[a] = new b(a))
    }
fabio@fabio-thinkpad ♥  bin/terser bug.js --keep_fnames=true -bmc
function a(n) {
    var r = e(this);
    return r[n] || (r[n] = new b(n));
}
```

**Comment by JonWallsten** [comment] 2019-10-13 15:59
@fabiosantoscode: I'll get you the JS input tomorrow at work!

**Comment by fabiosantoscode** [comment] 2019-10-13 16:01
Thanks @JonWallsten, it's really important for me to be able see the inputs, I realise that it can be hard to get them sometimes.

For example in #490, @kopax can't control the Terser options which makes reproducing a bug extra hard. Nice defaults are great, but not having an escape hatch for these situations isn't so great :/

**Comment by JonWallsten** [comment] 2019-10-13 16:08
@fabiosantoscode: Just realized I have my computer with me at home. I'll update this post with the code in a couple of minutes.

**Comment by kopax** [comment] 2019-10-13 17:21
> For example in #490, @kopax can't control the Terser options which makes reproducing a bug extra hard. Nice defaults are great, but not having an escape hatch for these situations isn't so great :/

What do you mean ? I was able to `minify: false` by editing the `node_modules`, but I can't control how react-styleguidist is using and forcing terser in production. But I can help you get a test case in local and show you where the switch is, it's about 30sec work.

**Comment by herberttn** [comment] 2019-10-14 12:55
> @herberttn I can't reproduce with your example:

Yeah, I couldn't get a simple enough snippet that presents the problem yet. Unfortunately I can only get the glitch to come up on a full build of my complete project (which is not open source). The snippet that I've posted here is just the piece of code that shows the problem, and I'm certain that it only occurs within a specific AST.

As soon as I can get a good reproduction I'll create an open repository and post here.

**Comment by fabiosantoscode** [comment] 2019-10-15 13:46
I really need to write a package that tries multiple minification options etc and tries to reproduce a bug by removing pieces of AST one by one :) lots of big applications get Terser errors and they're not reproducible in smaller builds.

**Comment by fabiosantoscode** [comment] 2019-10-15 14:00
@herberttn please try again with v4.3.9 which has been released right now and @ me to tell me if it fixed the issue.

**Comment by fabiosantoscode** [comment] 2019-10-15 16:35
Sorry, I should've directed my request to @JonWallsten

**Comment by JonWallsten** [comment] 2019-10-15 16:43
@fabiosantoscode: I'll check tomorrow morning. If it doesn't work maybe I can help you debug. My project is also private but we'll figure it out.

**Comment by JonWallsten** [comment] 2019-10-16 04:58
@fabiosantoscode: It works fine again! Thanks a lot!

**Comment by JonWallsten** [comment] 2019-10-16 05:34
@fabiosantoscode: It might have lead to another issue unfortunately. I'll try to get more details and update this answer when I do.

**Comment by JonWallsten** [comment] 2019-10-16 08:12
So, I've finally found the issue. It's old JavaScript code barely converted to TypeScript, then compiled to javascript again. There's a lot of code, because I didn't want to leave anything out. But the important stuff are the following:

The issue is that `c` is redefined in an inner function scope.
In the outer function (`uriTemplateSubstitution`) scope `c` is a `string`. In the inner function (`subFunction `) `c` is assigned to the `function` `_loop_1`.
`_loop_1` is a function created by the TypeScript compiler with the content of a the loop. Not sure why they to that.

**Source code:**
```javascript
function uriTemplateSubstitution (specs: string, escape: OasTemplateEscapeMode, template: string, compatibiltyMode: boolean) {
    let modifier = '';
    let separator = ',';
    if (uriTemplateGlobalModifiers[specs.charAt(0)]) {
        modifier = specs.charAt(0);
        specs = specs.substring(1);
    }
    let prefix = '';
    let shouldEscape = true;
    let showVariables = false;
    let uniqueVariables = false;
    let trimEmptyString = false;
    let explodeSeparator = ',';

    if (modifier === '+') {
        shouldEscape = false;
    } else if (modifier === '.') {
        prefix = '.';
        separator = '.';
    } else if (modifier === '/') {
        prefix = '/';
        separator = '/';
    } else if (modifier === '#') {
        prefix = '#';
        shouldEscape = false;
    } else if (modifier === ';') {
        prefix = ';';
        separator = ';';
        showVariables = true;
        trimEmptyString = true;
    } else if (modifier === '?') {
        prefix = '?';
        separator = '&';
        showVariables = true;
    } else if (modifier === '&') {
        prefix = '&';
        separator = '&';
        showVariables = true;
    } else if (modifier === '§') {
        prefix = ' ';
        separator = ' ';
        showVariables = true;
        uniqueVariables = true;
        trimEmptyString = true;
        explodeSeparator = '';
    } else if (modifier === '*') {
        separator = '';
        trimEmptyString = true;
        explodeSeparator = '';
    } else if (modifier === '|') {
        separator = new OasUriTemplate('{sep}', escape).fillFromObject({ sep: ' or ' });
    } else if (modifier === '@') {
        separator = new OasUriTemplate('{sep}', escape).fillFromObject({ sep: ' and ' });
    }

    let varMacro: MacroEntry;
    let macarr = [];
    const varSpecs = [];
    const varList = specs.split(',');
    for (let ii = 0; ii < varList.length; ii++) {
        let varName = varList[ii];

        /* Parse macros on the form $XXX(variable) */
        macarr = constants.regExpRFC6570Macro.exec(varName);
        varMacro = new MacroEntry();
        if (macarr != null) {
            // We have a macro
            varMacro.source = varName;
            varMacro.operations = macarr[1];
            varMacro.name = varName = macarr[2];
        } else {
            // No macro found, setup a NOP
            varMacro.name = varName;
            varMacro.source = '$(' + varName + ')';
            varMacro.operations = '';
        }
        let truncate = null;
        if (varName.indexOf(':') !== -1) {
            const parts = varName.split(':');
            varMacro.name = varName = parts[0];
            truncate = parseInt(parts[1], 10);
        }
        let explode = false;
        while (uriTemplateSuffices[varName.charAt(varName.length - 1)]) {
            const sx = varName.charAt(varName.length - 1);
            // Only '*' (explode) supported
            if (sx === '*') {
                explode = true;
            }
            varMacro.name = varName = varName.substring(0, varName.length - 1);
        }

        // Verify the macro enComplete or drop the macro entry
        varMacro = verifyMacro(varMacro, shouldEscape, escape, compatibiltyMode);


        const varSpec = new VariableSpec();
        varSpec.truncate = truncate;
        varSpec.explode = explode;
        varSpec.macro = varMacro;

        // Check the syntax a bit, if varName contains $ or ) something is wrong, e.g. {$o(t1,t2)} instead of the correct {$o(t1),$o(t2)}
        if (varSpec.macro.name.indexOf('$') > 0 || varSpec.macro.name.indexOf(')') > 0) {
            log.error("OasUriTemplate:uriTemplateSubstitution - Invalid template format for template '" + template + "' at offset " + template.indexOf(varSpec.macro.name));
        }

        varSpecs.push(varSpec);
    }
    const checkUnique = function (name: string, uniqueCheck: Object) {
        if (!uniqueVariables) {
            return;
        }
        if (uniqueCheck[name] != null) {
            log.error("OasUriTemplate:uriTemplateSubstitution - Invalid input to template '" + template + "', " + name + ' must be unique in output');
        }
        uniqueCheck[name] = true;
    };
    const checkSingle = function (mac: MacroEntry, collector: InvalidArgumentsCollector) {
        if (mac.operations.indexOf('s') >= 0) {
            // Not permitted to use array or object
            if (collector) {
                collector.logError(mac.name, 'multiple_values');
            } else {
                log.error("OasUriTemplate:uriTemplateSubstitution - Invalid input to template '" + template + "', " + mac.name + ' must be a single value, not an array or object');
            }
        }
    };
    const subFunction = function (valueFunction: (name: string) => any, collector: InvalidArgumentsCollector, extraFeedback: MacroFeedback): string | boolean {
        let result = '';
        const uniqueCheck = {};
        let startIndex = 0;
        for (let i = 0; i < varSpecs.length; i++) {
            const spec = varSpecs[i];
            const mac: MacroEntry = spec.macro;

            let value = valueFunction(spec.macro.name);

            // Return info about the macro
            extraFeedback.mac = mac;
            if (mac.operations.length === 1 && mac.operations[0] === '!' || mac.operations[0] === 'c' || mac.operations[0] === 'e') {
                // Macro is a condition start/end
                if (mac.operations[0] === 'c') {
                    return mac.valueExtractor(mac.arrayExtractor(value));
                }
                if (mac.operations[0] === '!') {
                    return !mac.valueExtractor(mac.arrayExtractor(value));
                }
                // Should never see this value since the {$e(test)} is never used
                return 'UNUSED VALUE, SHOULD NEVER BE SEEN';
            }

            if (mac.suppressPassiveValues) {
                if (value instanceof OasExtendedValue || value instanceof OasExtendedValueArray) {
                    if (!value.active) {
                        // We shall suppress inactive values
                        value = '';
                    }
                }
            }
            // Invoke the array extractor to expand some data to array
            value = mac.arrayExtractor(value);
            if (value == null || (Array.isArray(value) && value.length === 0) ||
                (typeof value === 'object' && Object.keys(value).length === 0 && !isDate(value))) {
                // Argument is null or empty object or array, run required check if present
                // to show errors and count missing arguments. Ignore return value
                performEncoding(null, mac, collector);
                startIndex++;
                continue;
            }
            if (Array.isArray(value) && value.length === 1) {
                // Treat arrays  with a single entry as a simple value
                value = value[0];
            }
            if (i === startIndex) {
                result += prefix;
            } else {
                result += separator;
            }
            if (Array.isArray(value)) {
                // Preprocess the array and convert all data to primitive strings
                // Then remove all empty strings so that only existing values are left in the array
                const existingValues = [];
                value.forEach((val) => {
                    val = extractStringValue(mac, val);
                    if (val.length > 0) {
                        existingValues.push(val);
                    }
                });
                if (existingValues.length === 0) {
                    // Leave at least one empty string
                    value = [''];
                } else {
                    // Keep the "real" values
                    value = existingValues;
                }
                checkSingle(spec.macro, collector);
                if (showVariables) {
                    result += spec.macro.name + '=';
                    checkUnique(spec.macro.name, uniqueCheck);
                }
                for (let j = 0; j < value.length; j++) {
                    if (j > 0) {
                        result += spec.explode ? separator : explodeSeparator;
                        if (spec.explode && showVariables) {
                            result += spec.macro.name + '=';
                            checkUnique(spec.macro.name, uniqueCheck);
                        }
                    }
                    result += performEncoding(value[j], mac, collector);
                }
            } else if (typeof value === 'object' && !isDate(value) && !(value instanceof OasExtendedValue)) {
                checkSingle(spec.macro, collector);
                if (showVariables && !spec.explode) {
                    result += spec.macro.name + '=';
                    checkUnique(spec.macro.name, uniqueCheck);
                }
                let first = true;
                Object.keys(value).forEach((key) => {
                    if (!first) {
                        result += spec.explode ? separator : explodeSeparator;
                    }
                    first = false;
                    result += performEncoding(key, mac, collector);
                    result += spec.explode ? '=' : ',';
                    result += performEncoding(value[key], mac, collector);
                });
            } else {
                if (showVariables) {
                    result += spec.macro.name;
                    checkUnique(spec.macro.name, uniqueCheck);
                    if (!trimEmptyString || value !== '') {
                        result += '=';
                    }
                }
                if (spec.truncate != null) {
                    value = value.substring(0, spec.truncate);
                }
                result += performEncoding(value, mac, collector);
            }
        }
        return result;
    };
    (subFunction as any).varSpecs = varSpecs;
    return {
        prefix: prefix,
        substitution: subFunction
    };
}
```

**Compiled code:**
```javascript
function uriTemplateSubstitution(specs, escape, template, compatibiltyMode) {
    var modifier = '';
    var separator = ',';
    if (uriTemplateGlobalModifiers[specs.charAt(0)]) {
        modifier = specs.charAt(0);
        specs = specs.substring(1);
    }
    var prefix = '';
    var shouldEscape = true;
    var showVariables = false;
    var uniqueVariables = false;
    var trimEmptyString = false;
    var explodeSeparator = ',';
    if (modifier === '+') {
        shouldEscape = false;
    }
    else if (modifier === '.') {
        prefix = '.';
        separator = '.';
    }
    else if (modifier === '/') {
        prefix = '/';
        separator = '/';
    }
    else if (modifier === '#') {
        prefix = '#';
        shouldEscape = false;
    }
    else if (modifier === ';') {
        prefix = ';';
        separator = ';';
        showVariables = true;
        trimEmptyString = true;
    }
    else if (modifier === '?') {
        prefix = '?';
        separator = '&';
        showVariables = true;
    }
    else if (modifier === '&') {
        prefix = '&';
        separator = '&';
        showVariables = true;
    }
    else if (modifier === '§') {
        prefix = ' ';
        separator = ' ';
        showVariables = true;
        uniqueVariables = true;
        trimEmptyString = true;
        explodeSeparator = '';
    }
    else if (modifier === '*') {
        separator = '';
        trimEmptyString = true;
        explodeSeparator = '';
    }
    else if (modifier === '|') {
        separator = new OasUriTemplate('{sep}', escape).fillFromObject({ sep: ' or ' });
    }
    else if (modifier === '@') {
        separator = new OasUriTemplate('{sep}', escape).fillFromObject({ sep: ' and ' });
    }
    var varMacro;
    var macarr = [];
    var varSpecs = [];
    var varList = specs.split(',');
    for (var ii = 0; ii < varList.length; ii++) {
        var varName = varList[ii];
        /* Parse macros on the form $XXX(variable) */
        macarr = constants.regExpRFC6570Macro.exec(varName);
        varMacro = new MacroEntry();
        if (macarr != null) {
            // We have a macro
            varMacro.source = varName;
            varMacro.operations = macarr[1];
            varMacro.name = varName = macarr[2];
        }
        else {
            // No macro found, setup a NOP
            varMacro.name = varName;
            varMacro.source = '$(' + varName + ')';
            varMacro.operations = '';
        }
        var truncate = null;
        if (varName.indexOf(':') !== -1) {
            var parts = varName.split(':');
            varMacro.name = varName = parts[0];
            truncate = parseInt(parts[1], 10);
        }
        var explode = false;
        while (uriTemplateSuffices[varName.charAt(varName.length - 1)]) {
            var sx = varName.charAt(varName.length - 1);
            // Only '*' (explode) supported
            if (sx === '*') {
                explode = true;
            }
            varMacro.name = varName = varName.substring(0, varName.length - 1);
        }
        // Verify the macro enComplete or drop the macro entry
        varMacro = verifyMacro(varMacro, shouldEscape, escape, compatibiltyMode);
        var varSpec = new VariableSpec();
        varSpec.truncate = truncate;
        varSpec.explode = explode;
        varSpec.macro = varMacro;
        // Check the syntax a bit, if varName contains $ or ) something is wrong, e.g. {$o(t1,t2)} instead of the correct {$o(t1),$o(t2)}
        if (varSpec.macro.name.indexOf('$') > 0 || varSpec.macro.name.indexOf(')') > 0) {
            oaslog_class_1.oasLog.error("OasUriTemplate:uriTemplateSubstitution - Invalid template format for template '" + template + "' at offset " + template.indexOf(varSpec.macro.name));
        }
        varSpecs.push(varSpec);
    }
    var checkUnique = function (name, uniqueCheck) {
        if (!uniqueVariables) {
            return;
        }
        if (uniqueCheck[name] != null) {
            oaslog_class_1.oasLog.error("OasUriTemplate:uriTemplateSubstitution - Invalid input to template '" + template + "', " + name + ' must be unique in output');
        }
        uniqueCheck[name] = true;
    };
    var checkSingle = function (mac, collector) {
        if (mac.operations.indexOf('s') >= 0) {
            // Not permitted to use array or object
            if (collector) {
                collector.logError(mac.name, 'multiple_values');
            }
            else {
                oaslog_class_1.oasLog.error("OasUriTemplate:uriTemplateSubstitution - Invalid input to template '" + template + "', " + mac.name + ' must be a single value, not an array or object');
            }
        }
    };
    var subFunction = function (valueFunction, collector, extraFeedback) {
        var result = '';
        var uniqueCheck = {};
        var startIndex = 0;
        var _loop_1 = function (i) {
            var spec = varSpecs[i];
            var mac = spec.macro;
            var value = valueFunction(spec.macro.name);
            // Return info about the macro
            extraFeedback.mac = mac;
            if (mac.operations.length === 1 && mac.operations[0] === '!' || mac.operations[0] === 'c' || mac.operations[0] === 'e') {
                // Macro is a condition start/end
                if (mac.operations[0] === 'c') {
                    return { value: mac.valueExtractor(mac.arrayExtractor(value)) };
                }
                if (mac.operations[0] === '!') {
                    return { value: !mac.valueExtractor(mac.arrayExtractor(value)) };
                }
                return { value: 'UNUSED VALUE, SHOULD NEVER BE SEEN' };
            }
            if (mac.suppressPassiveValues) {
                if (value instanceof oasextendedvalue_class_1.OasExtendedValue || value instanceof oasextendedvaluearray_class_1.OasExtendedValueArray) {
                    if (!value.active) {
                        // We shall suppress inactive values
                        value = '';
                    }
                }
            }
            // Invoke the array extractor to expand some data to array
            value = mac.arrayExtractor(value);
            if (value == null || (Array.isArray(value) && value.length === 0) ||
                (typeof value === 'object' && Object.keys(value).length === 0 && !utils_1.isDate(value))) {
                // Argument is null or empty object or array, run required check if present
                // to show errors and count missing arguments. Ignore return value
                performEncoding(null, mac, collector);
                startIndex++;
                return "continue";
            }
            if (Array.isArray(value) && value.length === 1) {
                // Treat arrays  with a single entry as a simple value
                value = value[0];
            }
            if (i === startIndex) {
                result += prefix;
            }
            else {
                result += separator;
            }
            if (Array.isArray(value)) {
                // Preprocess the array and convert all data to primitive strings
                // Then remove all empty strings so that only existing values are left in the array
                var existingValues_1 = [];
                value.forEach(function (val) {
                    val = extractStringValue(mac, val);
                    if (val.length > 0) {
                        existingValues_1.push(val);
                    }
                });
                if (existingValues_1.length === 0) {
                    // Leave at least one empty string
                    value = [''];
                }
                else {
                    // Keep the "real" values
                    value = existingValues_1;
                }
                checkSingle(spec.macro, collector);
                if (showVariables) {
                    result += spec.macro.name + '=';
                    checkUnique(spec.macro.name, uniqueCheck);
                }
                for (var j = 0; j < value.length; j++) {
                    if (j > 0) {
                        result += spec.explode ? separator : explodeSeparator;
                        if (spec.explode && showVariables) {
                            result += spec.macro.name + '=';
                            checkUnique(spec.macro.name, uniqueCheck);
                        }
                    }
                    result += performEncoding(value[j], mac, collector);
                }
            }
            else if (typeof value === 'object' && !utils_1.isDate(value) && !(value instanceof oasextendedvalue_class_1.OasExtendedValue)) {
                checkSingle(spec.macro, collector);
                if (showVariables && !spec.explode) {
                    result += spec.macro.name + '=';
                    checkUnique(spec.macro.name, uniqueCheck);
                }
                var first_1 = true;
                Object.keys(value).forEach(function (key) {
                    if (!first_1) {
                        result += spec.explode ? separator : explodeSeparator;
                    }
                    first_1 = false;
                    result += performEncoding(key, mac, collector);
                    result += spec.explode ? '=' : ',';
                    result += performEncoding(value[key], mac, collector);
                });
            }
            else {
                if (showVariables) {
                    result += spec.macro.name;
                    checkUnique(spec.macro.name, uniqueCheck);
                    if (!trimEmptyString || value !== '') {
                        result += '=';
                    }
                }
                if (spec.truncate != null) {
                    value = value.substring(0, spec.truncate);
                }
                result += performEncoding(value, mac, collector);
            }
        };
        for (var i = 0; i < varSpecs.length; i++) {
            var state_1 = _loop_1(i);
            if (typeof state_1 === "object")
                return state_1.value;
        }
        return result;
    };
    subFunction.varSpecs = varSpecs;
    return {
        prefix: prefix,
        substitution: subFunction
    };
}
```
**Minified code:** 
```javascript
function k(e, t, n, o) {
    var a = ""
        , r = ",";
    w[e.charAt(0)] && (a = e.charAt(0),
    e = e.substring(1));
    var i, c = "", f = !0, h = !1, g = !1, y = !1, v = ",";
    "+" === a ? f = !1 : "." === a ? (c = ".",
    r = ".") : "/" === a ? (c = "/",
    r = "/") : "#" === a ? (c = "#",
    f = !1) : ";" === a ? (c = ";",
    r = ";",
    h = !0,
    y = !0) : "?" === a ? (c = "?",
    r = "&",
    h = !0) : "&" === a ? (c = "&",
    r = "&",
    h = !0) : "§" === a ? (c = " ",
    r = " ",
    h = !0,
    g = !0,
    y = !0,
    v = "") : "*" === a ? (r = "",
    y = !0,
    v = "") : "|" === a ? r = new F("{sep}",t).fillFromObject({
        sep: " or "
    }) : "@" === a && (r = new F("{sep}",t).fillFromObject({
        sep: " and "
    }));
    for (var _ = [], O = [], T = e.split(","), j = 0; j < T.length; j++) {
        var P = T[j];
        _ = s.regExpRFC6570Macro.exec(P),
        i = new m,
        null != _ ? (i.source = P,
        i.operations = _[1],
        i.name = P = _[2]) : (i.name = P,
        i.source = "$(" + P + ")",
        i.operations = "");
        var E = null;
        if (-1 !== P.indexOf(":")) {
            var R = P.split(":");
            i.name = P = R[0],
            E = parseInt(R[1], 10)
        }
        for (var S = !1; V[P.charAt(P.length - 1)]; )
            "*" === P.charAt(P.length - 1) && (S = !0),
            i.name = P = P.substring(0, P.length - 1);
        i = D(i, f, t, o);
        var I = new b;
        I.truncate = E,
        I.explode = S,
        I.macro = i,
        (I.macro.name.indexOf("$") > 0 || I.macro.name.indexOf(")") > 0) && d.oasLog.error("OasUriTemplate:uriTemplateSubstitution - Invalid template format for template '" + n + "' at offset " + n.indexOf(I.macro.name)),
        O.push(I)
    }
    var L = function(e, t) {
        g && (null != t[e] && d.oasLog.error("OasUriTemplate:uriTemplateSubstitution - Invalid input to template '" + n + "', " + e + " must be unique in output"),
        t[e] = !0)
    }
        , C = function(e, t) {
        e.operations.indexOf("s") >= 0 && (t ? t.logError(e.name, "multiple_values") : d.oasLog.error("OasUriTemplate:uriTemplateSubstitution - Invalid input to template '" + n + "', " + e.name + " must be a single value, not an array or object"))
    }
        , k = function(e, t, n) {
        for (var o = "", a = {}, i = 0, c = function(s) {
            var d = O[s]
                , f = d.macro
                , g = e(d.macro.name);
            if (n.mac = f,
            1 === f.operations.length && "!" === f.operations[0] || "c" === f.operations[0] || "e" === f.operations[0])
                return "c" === f.operations[0] ? {
                    value: f.valueExtractor(f.arrayExtractor(g))
                } : "!" === f.operations[0] ? {
                    value: !f.valueExtractor(f.arrayExtractor(g))
                } : {
                    value: "UNUSED VALUE, SHOULD NEVER BE SEEN"
                };
            if (f.suppressPassiveValues && (g instanceof l.OasExtendedValue || g instanceof u.OasExtendedValueArray) && (g.active || (g = "")),
            null == (g = f.arrayExtractor(g)) || Array.isArray(g) && 0 === g.length || "object" == typeof g && 0 === Object.keys(g).length && !p.isDate(g))
                return x(null, f, t),
                i++,
                "continue";
            if (Array.isArray(g) && 1 === g.length && (g = g[0]),
            o += s === i ? c : r,
            Array.isArray(g)) {
                var m = [];
                g.forEach((function(e) {
                    (e = M(f, e)).length > 0 && m.push(e)
                }
                )),
                g = 0 === m.length ? [""] : m,
                C(d.macro, t),
                h && (o += d.macro.name + "=",
                L(d.macro.name, a));
                for (var b = 0; b < g.length; b++)
                    b > 0 && (o += d.explode ? r : v,
                    d.explode && h && (o += d.macro.name + "=",
                    L(d.macro.name, a))),
                    o += x(g[b], f, t)
            } else if ("object" != typeof g || p.isDate(g) || g instanceof l.OasExtendedValue)
                h && (o += d.macro.name,
                L(d.macro.name, a),
                y && "" === g || (o += "=")),
                null != d.truncate && (g = g.substring(0, d.truncate)),
                o += x(g, f, t);
            else {
                C(d.macro, t),
                h && !d.explode && (o += d.macro.name + "=",
                L(d.macro.name, a));
                var _ = !0;
                Object.keys(g).forEach((function(e) {
                    _ || (o += d.explode ? r : v),
                    _ = !1,
                    o += x(e, f, t),
                    o += d.explode ? "=" : ",",
                    o += x(g[e], f, t)
                }
                ))
            }
        }, s = 0; s < O.length; s++) {
            var d = c(s);
            if ("object" == typeof d)
                return d.value
        }
        return o
    };
    return k.varSpecs = O,
    {
        prefix: c,
        substitution: k
    }
}
```

**Comment by fabiosantoscode** [comment] 2019-10-16 10:47
I will certainly dig into this :) thanks for reporting.

**Comment by fabiosantoscode** [comment] 2019-10-16 10:47
(when I have the time)

**Comment by fabiosantoscode** [comment] 2019-10-17 12:36
I will dig into this indeed :) can't have these bugs in Terser, so why close?

**Comment by JonWallsten** [comment] 2019-10-17 13:00
@fabiosantoscode: Sorry, wasn't sure you wanted to have open tickets that you know you won't work on for a while.

**Comment by fabiosantoscode** [comment] 2019-10-21 11:23
It's helpful to keep these open. When I have the time to work on terser I look at the first couple of open issue pages for things that need fixing or doing first. I can't remember every bug and feature request :)

**Comment by JonWallsten** [comment] 2019-10-23 06:49
@fabiosantoscode: Let me know if you need anything else when you're debugging it later on.

**Comment by fabiosantoscode** [comment] 2019-11-10 13:26
@JonWallsten I can't reproduce. Could you please try again with v4.3.11? I might've fixed this while fixing something else.

It might also be that it's not reproducible without minifying the code outside of the problematic function as well. Sometimes this happens.

**Comment by fabiosantoscode** [comment] 2019-11-10 13:28
When I put the function into terser with default settings, it came out as:

```javascript
    }, u = 0; u < d.length; u++) {                
        var f = i(u);                             
        if ("object" == typeof f) return f.value; 
    }                                             
    return t;                                     
};                                                
return A.varSpecs = d, {                          
    prefix: l,                                    
    substitution: A                               
};                                                
```

As you can see, instead of having `prefix: c` and `c(...)`, `l` is the string and `i` is the function, and they wouldn't collide anyway because they're in separate scopes.

**Comment by JonWallsten** [comment] 2019-11-11 07:46
@fabiosantoscode: Just tried 4.4.0. It works fine! However I could not reproduce the error with 4.3.5 anymore, so something else might have changed as well. I would say you can close this, and then someone can open up a new one if it happens again.

**Closed** 2019-11-11 07:46 UTC
Labels: bug
