### ISSUE TITLE
use terser 5, it show error 'TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined'

### ISSUE THREAD

**Issue by jerryc127** [terser/terser#879] opened 2020-11-23 18:22 UTC
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**

**Complete CLI command or `minify()` options used**

**`terser` input**

**`terser` output or error**

**Expected result**

I use the gulp to minify the js

when I use terser 4.8.0, It works fine.

but when I update to 5,

it shows the error 'TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined'

how to solve it?

**Comment by fabiosantoscode** [comment] 2020-11-27 09:29
Terser 5 changed its interface, and it's now asynchronous. Your gulp plugin might not support it. I'm closing the issue because there's no reproduction and it's not related to Terser.

**Closed** 2020-11-27 09:29 UTC
