### ISSUE TITLE
ERROR: Unexpected character '#' – private class fields

### ISSUE THREAD

**Issue by AlttiRi** [terser/terser#702] opened 2020-05-17 16:02 UTC
I use in my code `#` for private class fields:

```js
class Main {
    static #foo = "FOO";

    static foo() {
        return Main.#foo;
    }

    #bar;
    constructor(bar = "bar") {
        this.#bar = bar;
    }

    get() {
        return Main.#foo + this.#bar;
    }
}

console.log(Main.foo());
console.log(new Main().get());
```

I use `terser --compress --mangle -o ./dist/main.min.js ./src/main.js` to minify it, but I get:
```
Parse error at ./src/main.js:2,11
    static #foo = "FOO";
           ^
ERROR: Unexpected character '#'
    at js_error (...\node_modules\terser\lib\parse.js:369:11)
    at parse_error (...\node_modules\terser\lib\parse.js:502:9)
    at Object.input (...\node_modules\terser\lib\parse.js:902:9)
    ...
```

Any good workaround? I don't want to remove `#` from my code and from the minified version too.

_Terser 4.6.13_

Although currently only [Chromuim](https://caniuse.com/#search=Private%20class%20fields) and Node.js support this I would prefer to have ability to minimaze the code without any change for them, and with Babel for the others.

**Comment by fabiosantoscode** [comment] 2020-05-17 16:15
I completely forgot to implement this! Only public fields are implemented right now. This isn't a stage 4 feature though so I'm technically not late.

It won't be quick or easy to implement this in Terser. There are many assumptions that it was making that are now invalid.

**Comment by Finesse** [comment] 2020-06-06 10:49
Also it would be great if Terser mangles the private property names. It's safe because the private properties aren't accessible from outside the class.

**Comment by fabiosantoscode** [comment] 2020-06-06 19:45
Yes, that is totally on my radar. The question is what interface you need to use to enable this.

**Comment by Anoesj** [comment] 2020-07-22 21:12
Private class fields are great! Any progress by any chance? 😁

**Comment by fabiosantoscode** [comment] 2020-07-23 08:48
Not really. Right now I'm working on ?. , there's a regression in compression quality which needs to be addressed, and Terser 5 has to be released.

**Comment by petterek** [comment] 2020-10-16 14:01
bit off topic for this.. but same error occurs  if you try to do 
`somefunctThatCanBeNull.?()`

**Comment by fabiosantoscode** [comment] 2020-10-16 14:19
@petterek Update Terser :)

**Comment by Boefjim** [comment] 2020-11-06 09:06
Any progress on this yet?
Would love to be able to use this with terser

**Comment by fabiosantoscode** [comment] 2020-11-06 09:43
Hey there! This is still a stage 3 proposal, and quite tricky to implement. I'll give it a real go when it's stage 4

**Comment by frankc60** [comment] 2020-11-22 17:25
great, thanks. It would be really helpful to have this working.

**Comment by tchetwin** [comment] 2020-12-11 09:28
Private fields are [shipping in WebKit](https://webkit.org/blog/11364/release-notes-for-safari-technology-preview-117/) paving the way for Stage 4 (two shipping implementations) in a forthcoming TC39 meeting.

**Comment by tchetwin** [comment] 2021-01-08 12:33
I'd like to support the effort to make this feature available in Terser.

@L2jLiga created https://github.com/terser/terser/pull/780 to support the `#` character appearing in class property and method names.

> not really sure how to make parser throw error when property starts with "#" not in classes.

Based on ^ it *may* allow non-class usage of `#privates`, but it's not clear to me to what extent Terser should be validating correctness of the input to begin with so I'm not sure if this is a blocker.



I can imagine future optimisations in Terser that could lean in to the fact something is not accessible from outside the class, but it would be good to have "pass-through" support initially. What further changes (if any) are required to progress that PR?

---

(aside: we have a couple of alternate Issues tracking this, namely #897 and #349. It would be good to close those in favour of this Issue and maybe update the title to make it authoritative)

**Comment by fabiosantoscode** [comment] 2021-01-08 15:00
I'll admit that I never considered this.

Terser, when convenient, adopts a garbage in garbage out approach because its job is not to validate correct syntax or ensure that you chose the correct ecma version for your script.

Considering this, @L2jLiga 's PR seems way more legit than when I saw it at first. Additionally we should be checking any transforms that affect property access/assignment and make sure that they don't read the # blindly. There shouldn't be too many cases.

**Comment by rricard** [comment] 2021-01-08 17:34
As I stated in https://github.com/terser/terser/pull/780#discussion_r554089946 I would be interested in helping land this: I can work on a set of additional checks to cover more edge cases if you would be interested in such PR.

**Comment by fabiosantoscode** [comment] 2021-01-08 19:21
@rricard your help is very welcome!

I've created the branch wip/private-properties including the work in #780, feel free to push a PR to it.

It's possible that nothing needs to be done at all from here on (if there are zero places where the assumption that a property happens to be an identifier breaks).

**Comment by T3Lakuna** [comment] 2021-01-11 05:53
I've closed #702 in favor of this.

**Comment by rricard** [comment] 2021-01-11 12:03
> Terser, when convenient, adopts a garbage in garbage out approach because its job is not to validate correct syntax or ensure that you chose the correct ecma version for your script.

I am seeing some issues on incorrect input. If I give the following input out of a class: `this.#foo = "bad"`, I get back `this["#foo"] = "bad"`. 

My question here is, do we expect the "garbage" to be identical (instinctively, I'd say yes) or do we tolerate different outputs?  My problem with this behavior is that terser is making some wrong javascript implicitely okay. The other problem is that if we want to fix it we need to do a better job in the parser at differentiating names from private names...

I can work on that but I would like to know what you think @fabiosantoscode before going into that...

**Comment by fabiosantoscode** [comment] 2021-01-12 20:24
Yes, that output is wrong. It's probably a bug in the DEFPRINT for AST_Dot

**Comment by rricard** [comment] 2021-01-13 11:33
The behavior behind this is that if it were a standard property, the # char would require it to be wrapped into a string expression to be a correct identifier. That is why the pr you merged into the wip branch is analysing the call site (in or outside a class declaration) to know whether to quote or not... as that example I gave you is out of a class declaration, it got quoted. The only way that I see to mitigate that is to distinguish during parse time private names from non private names. I am going to attempt doing this but it might become a bigger pr...

**Comment by fabiosantoscode** [comment] 2021-01-13 14:33
I gave it some more thought and had a look at the implementation.

It's perfectly fine to keep as is (IE forbid private properties outside classes). It would only become a problem if people wanted to wrap their code inside a class and have access to its private properties. But I don't think people are going to do it at least for now.

**Comment by rricard** [comment] 2021-01-13 15:14
I will add more test coverage here and continue listing similar behavior in my pr so we can fix it afterwards in a follow-on pr. Thank you for the feedback

**Comment by rricard** [comment] 2021-01-14 13:56
I actually found another issue while playing around with it, this one is more concerning:

Given the following input:

```js
class A {
  #a = "pass";
  ["#a"] = "fail"
  test() { return this.#a }
}
```

Will end up being:

```js
class A {
  #a = "pass";
  ["#a"] = "fail"
  test() { return this["#a"] }
}
```

Note that the input is perfectly ok and shouldn't be transformed like this. I will now try to correct the implementation as this is a bigger correctness issue.

**Comment by fabiosantoscode** [comment] 2021-01-14 19:43
I guess this is caused by the same issue. I think I know what's going on, let me have a look later and I'll push a commit to the WIP branch.

**Comment by rricard** [comment] 2021-01-14 20:17
It is the same issue, I have a pretty good idea why this is doing this but you might have more insights on how to fix it.

**Comment by fabiosantoscode** [comment] 2021-01-14 22:07
@rricard I pushed a simple fix. The is_basic_identifier, is_identifier_string functions needed _property variants. I added them.

Now `const #x = 4; console.log(#x)` is valid and minifies to `console.log(4)` but don't tell anyone ;)

**Comment by rricard** [comment] 2021-01-14 22:12
Excellent! Simple fixes are great. I will keep that optimization quiet but I will probably add it as a test so the behavior is known in there if you don't mind! Thank you again for taking the time to look at this; I wish I had figured out that one myself! I was adding a new token kind and had to do a bunch of conditional handling everywhere to make that work...

**Comment by fabiosantoscode** [comment] 2021-01-15 09:03
Please don't add the wrong syntax fix. It's an undesired feature so it shouldn't be tested. The same, but without the #, is already thoroughly tested

**Comment by rricard** [comment] 2021-01-15 12:47
I just tried your fix, unfortunately if you declare a property with a string like in https://github.com/terser/terser/issues/702#issuecomment-760212311 it will get transformed to a private field. Given that last example, here is the output:

```js
class A {
  #a = "pass";
  #a = "fail"
  test() { return this.#a }
}

**Comment by fabiosantoscode** [comment] 2021-01-15 15:01
I guess this means that a separate class inheriting AST_Dot is needed.

**Comment by rricard** [comment] 2021-01-15 15:31
I am attempting a flag right now but yes that might make more sense...

**Comment by rricard** [comment] 2021-01-15 16:24
I think I am onto something here: https://github.com/terser/terser/commit/ef7f2502c11176624a37a5a5a8d95478793fc0b1

**Comment by fabiosantoscode** [comment] 2021-01-15 19:07
I added a comment in the commit. It's probably best to inherit AST_PropertyAccess to avoid instanceof checks.

**Comment by rricard** [comment] 2021-01-15 22:39
Agreed, will change that on Monday. Thanks!

**Comment by rricard** [comment] 2021-01-18 11:07
I removed all instanceof checks that I previously introduced. This results in a bit more code duplication but private properties and methods are different enough to warrant this duplication

**Comment by fabiosantoscode** [comment] 2021-01-18 11:50
Indeed. Best to opt in to transforms than to opt out.

**Comment by rricard** [comment] 2021-01-18 13:01
#913 is ready for a proper review impl-wise. I still want to look into more tests before merging though.

**Comment by fabiosantoscode** [comment] 2021-01-18 13:06
I'll have a look!

**Closed** 2021-01-28 10:44 UTC
