### ISSUE TITLE
Constructor names prefixed with "js_"

### ISSUE THREAD

**Issue by CreativeBulma** [terser/terser#492] opened 2019-10-13 11:05 UTC
Hi,

when using Terser with following webpack settings:
```js
optimization: {
		minimizer: [new TerserPlugin({
			sourceMap: false,
			terserOptions: {
				compress: true,
				keep_fnames: true,
				ie8: false,
				output: {
					comments: false,
				},
			}
		})],
	}
```

my classe's constructor names are prefixed by "js_". I d'ont understand why ? How can I prevent them to get prefixed and keep the original class name?

EDIT: only classnames  from node_modules are prefixed. Not the one from my own code.

Regards,

**Comment by fabiosantoscode** [comment] 2019-10-13 15:40
Does this still happen when you turn Terser off? Because there's nothing in it that changes names besides mangling them.

**Comment by CreativeBulma** [comment] 2019-10-13 15:43
When I turn Terser off my function names and class names are minified and I lose the original name

**Comment by fabiosantoscode** [comment] 2019-10-13 16:02
But if you remove the minifier step completely, can you still reproduce?

**Comment by fabiosantoscode** [comment] 2019-12-01 14:09
Closing since it is very unlikely that Terser is adding prefixes to names.

**Closed by fabiosantoscode** 2019-12-01 14:09 UTC
