### ISSUE TITLE
Unused functions with more than one static property are not removed

### ISSUE THREAD

**Issue by atkinchris** [terser/terser#776] opened 2020-08-08 16:46 UTC
**Bug report**

Unused functions are not removed when code is minified, if they:
* have static properties _and_ are assigned to a value that's never used
* have more that one static property

I want to understand if this is a bug with Terser, or something it's expected not to handle - and if there's an option or annotation that can help Terser understand that these are safe to remove.

This has a real world implication for React components, which often have multiple static properties, for example `propTypes`, `defaultProps` and `displayName`, or are assigned to an unused `export` (for example, with higher-order functions, like `recompose`) - and will not be tree shaken from bundles created with Webpack and Terser.

**Version (complete output of `terser -V` or specific git commit)**

```
terser@5.0.0
```

**Complete CLI command or `minify()` options used**

Default `minify` options used.

**`terser` input**

```js
(function() {
  function cat() { return "🐈" }
  cat.noise = "meow"
  cat.name = "Catrick"
})()
```

**`terser` output or error**

```js
!function(){function n(){return"🐈"}n.noise="meow",n.name="Catrick"}();
```

**Expected result**

```js
// Nothing
```

**Code Example**

```js
const { minify } = require('terser')

async function test() {
  // Test Case: Passing
  let result = await minify(`
    (function() {
      function cat() { return "🐈" }
      // cat.noise = "meow"
      // const Cat = cat
    })()
  `)

  console.log('minifies without static and assignment', !result.code.includes('🐈'))

  // Test Case: Passing
  result = await minify(`
    (function() {
      function cat() { return "🐈" }
      cat.noise = "meow"
      // const Cat = cat
    })()
  `)

  console.log('minifies with static property only', !result.code.includes('🐈'))

  // Test Case: Passing
  result = await minify(`
    (function() {
      function cat() { return "🐈" }
      // cat.noise = "meow"
      const Cat = cat
    })()
  `)

  console.log('minifies with assignment only', !result.code.includes('🐈'))

  // Test Case: Failing
  result = await minify(`
    (function() {
      function cat() { return "🐈" }
      cat.noise = "meow"
      const Cat = cat
    })()
  `)

  console.log('minifies with both static property and assignment', !result.code.includes('🐈'))

  // Test Case: Failed
  result = await minify(`
    (function() {
      function cat() { return "🐈" }
      cat.noise = "meow"
      cat.name = "Catrick"
      // const Cat = cat
    })()
  `)

  console.log('minifies with multiple static properties', !result.code.includes('🐈'))
}

test().catch(console.error)
```

**Comment by atkinchris** [comment] 2020-08-09 21:13
I suspect this is related to https://github.com/terser/terser/issues/293.

**Comment by fabiosantoscode** [comment] 2020-08-11 22:38
Hello there!

I think it's actually a duplicate of #293 -- classes functions and object literals behave the same in this sense.

It's not a bug atm, I think it's something Terser never did.

That's a great point about this being important for React components, I didn't consider it.

I'll pay more attention to #293 but I have some esnext features to attend to first :)

**Closed by fabiosantoscode** 2020-08-11 22:38 UTC
