### ISSUE TITLE
Math undefined when compress inline=3

### ISSUE THREAD

**Issue by tomwetjens** [terser/terser#156] opened 2018-11-01 14:55 UTC
I am using CryptoJS which gets processed by terser through webpack. And I appear to be having a similar issue. I took the CryptoJS source code and managed to narrow it down to this case:
```
(function (root, factory) {
  root.CryptoJS = factory()
})(this, function () {
  var CryptoJS = CryptoJS || function (Math) {
    var C = {};
    C.demo = function(n) {
      return Math.ceil(n);
    };
    return C;
  }(Math);
  return CryptoJS
});
var result = this.CryptoJS.demo(1.3);
console.log(result);
```

I run it through terser manually: terser -c -- demo.js
And when I run it:

Expected (and verified without terser -c):
`2`

Actual:
`TypeError: Cannot read property 'ceil' of undefined`

This is the output by 'terser -c':
```
!function (root, factory) {
  var Math, CryptoJS;
  root.CryptoJS = CryptoJS = CryptoJS || (Math = Math, {
    demo: function (n) {
      return Math.ceil(n)
    }
  })
}(this);
var result = this.CryptoJS.demo(1.3);
console.log(result);
```

It appears that Math is used as variable name/default.

_Originally posted by @kzc in https://github.com/terser-js/terser/issues/91#issuecomment-435057896_

**Comment by kzc** [comment] 2018-11-01 15:55
This bug is related to `inline=3`. A workaround is to use `-c inline=2`.

This regression was introduced in `terser@3.10.7` in commit 0ad62120d6567e95e25909bef66e3d29120a128e.

**Note**: this bug also exists with `-c inline=3,passes=2` on older terser versions:

```
$ terser -V
terser 3.10.5

$ cat demo.js | terser -c passes=1 | node
2

$ cat demo.js | terser -c passes=2 | node
[stdin]:1
!function(root,factory){var CryptoJS,Math;root.CryptoJS=CryptoJS=CryptoJS||(Math=Math,{demo:function(n){return Math.ceil(n)}})}(this);var result=this.CryptoJS.demo(1.3);console.log(result);
                                                                                                                   ^
TypeError: Cannot read property 'ceil' of undefined
```

The yet to be merged PR #154 fixes this specific regression with default `minify` options. **However**, if `-c inline=3,passes=2` is set, then PR #154 will also fail. 

It's worth noting that `uglify-js` also has this bug with `passes=2`:

```
$ uglify-js -V
uglify-js 3.4.9

$ cat demo.js | uglify-js -c passes=1 | node
2

$ cat demo.js | uglify-js -c passes=2 | node
[stdin]:1
!function(root,factory){var CryptoJS,Math;root.CryptoJS=CryptoJS=CryptoJS||(Math=Math,{demo:function(n){return Math.ceil(n)}})}(this);var result=this.CryptoJS.demo(1.3);console.log(result);
                                                                                                                   ^
TypeError: Cannot read property 'ceil' of undefined
```

@fabiosantoscode There's no harm in merging PR #154 to fix default `minify` until this `-c inline=3,passes=2` bug is sorted out. Please leave this ticket open in the meantime.

**Comment by merrywhether** [comment] 2018-11-01 22:19
Oh sweet, I weirdly backed into this solution before finding this. I didn't suspect there was someone else out there sharing this particular setup combination. Looking forward to the release of this fix.

**Comment by tomwetjens** [comment] 2018-11-02 07:55
@kzc Thanks. I will try the suggested workaround for now.

**Comment by kzc** [comment] 2018-11-03 19:04
@tomwetjens @merrywhether Try `terser@3.10.10` out and report your findings.

There's a more comprehensive fix (#158) in the works, but it might not be necessary in your case.

**Comment by tomwetjens** [comment] 2018-11-04 13:49
@kzc solves the issue for me! thanks

**Comment by merrywhether** [comment] 2018-11-07 00:06
@kzc Works for me as well. Thanks!

**Comment by kzc** [comment] 2018-11-07 00:54
Good to know. 

We'll keep this issue until the real underlying inline problem is fixed. Although the approach in #158 didn't pan out, the tests from that PR can be reused in the eventual fix.

**Comment by fabiosantoscode** [comment] 2018-12-04 17:49
I think we should all (barring any issues with it) bare our names in this forum, and be able to speak equally.

**Comment by fabiosantoscode** [comment] 2019-09-25 12:20
This has been fixed by something else, and the example in https://github.com/terser/terser/pull/158#issuecomment-435687831 also works now too.

**Closed by fabiosantoscode** 2019-09-25 12:20 UTC
