### ISSUE TITLE
No way to prevent *just* trailing semicolon (output an expression)

### ISSUE THREAD

**Issue by tolmasky** [terser/terser#277] opened 2019-02-18 21:37 UTC
Not sure if bug or feature request. Depends on intended use I suppose.

The output of terser seems to always include a trailing semicolon: minify("(function() { return 5 })") => "(function{return 5});", which makes it hard to concat multiple results into one file as expressions: `"[" + result1 + "," + result2 + "]"`. I know I can do `{ output: { semicolons: false } }` to turn off ALL semicolons, but this seems like the wrong use for this option, and confusing for anyone looking at the code later.

My expectation would be that the "expression" option would also *output* an expression. I understand that the actual purpose seems to be to keep final expressions.

That being said, I think it makes sense to be able to tell the generation that you are expecting an expression or statement/program on output, depending on how you are planning on using the generated output. I can of course merely remove the trailing semicolon, but this is a potentially expensive post-processing operation (result.substr(0, -1)), and also pretty brittle and difficult to understand, vs.  a minify output option of `{ output: { expression: true } }` which would be more declarative and indicative of the intent, as well as faster than manipulating a potentially very large string. Such an option would mirror the parseExpression option in Babel.

**Comment by fabiosantoscode** [comment] 2019-02-23 03:35
This makes a ton of sense to me, as I love expressions and like their composability. But since you can always take out the semicolon at the end with a string operation, I'm not giving it much priority. Instead I'm giving it the "good first PR" label to encourage new people to get to know Terser and contribute to it.

My proposed solution is to add a `expression` option to the minify options. This would give you an error if your code is not already an expression, and remove the final semicolon in the output with a string operation or something that doesn't involve checking every print of a semicolon to see if it's the last one.

**Comment by jridgewell** [comment] 2021-09-06 22:25
I'm going to mark this as a duplicate of https://github.com/terser/terser/issues/540, which would also be solved by adding an `expression` option to terser.

**Closed by jridgewell** 2021-09-06 22:25 UTC
Labels: enhancement
