### ISSUE TITLE
String variables are joined to complete strings and duplicated after compression

### ISSUE THREAD

**Issue by mchukhriaiev** [terser/terser#792] opened 2020-08-17 15:54 UTC
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**
![image](https://user-images.githubusercontent.com/68418020/90413553-4a652100-e0b7-11ea-9f6f-644330cdfdec.png)

**Complete CLI command or `minify()` options used**
![image](https://user-images.githubusercontent.com/68418020/90413943-d0816780-e0b7-11ea-8598-3d05dbb9e498.png)

**Description**
All string variables which defined as concatination of another string variables are duplicated and represents as string values in the place of usage instead of concationation of obfuscated variables.
After Babel transformation it represents as concatination of variables.
After Babel transformation and Terser transformation it represents as complete strings.

**Reproduced on**
* NodeJS v12.13.1
* Rollup v2.25.0
* rollup-plugin-terser v7.0.0
* Terser v5.0.0
* Babel v7.11.0

**Steps to reproduce**
1. Configure RollUp with Terser without any additional Terser options (use default options)
2. Define and export string variable that values are concatenated with another string variable
![image](https://user-images.githubusercontent.com/68418020/90414670-c01dbc80-e0b8-11ea-933a-700c1697abc0.png)
![image](https://user-images.githubusercontent.com/68418020/90414936-125edd80-e0b9-11ea-84fd-a3795587bf52.png)
3. Import and pass concatenated variables as arguments of function
![image](https://user-images.githubusercontent.com/68418020/90415169-5eaa1d80-e0b9-11ea-90af-4c8e64018ec1.png)

**Actual behaviour**
After Terser compression:

1. exported variables presented as complete concatenated strings and not used anywhere
![image](https://user-images.githubusercontent.com/68418020/90415479-ceb8a380-e0b9-11ea-8797-04ef36c80ca1.png)

2. exported variables are duplicated and passed to the function as complete concatenated strings
![image](https://user-images.githubusercontent.com/68418020/90415594-f90a6100-e0b9-11ea-806b-89ea702310ed.png)

**Expected behaviour**

Concatenated string variables should looks like 
```js
var a='part-1',b=a+'/part-2',c=a+'/part-3';
S.log(b,c)
```
instead of
```js
var a='part-1',b='part-1/part-2',c='part-1/part-3';
S.log('part-1/part-2', 'part-1/part-3')
```

**Comment by fabiosantoscode** [comment] 2020-08-18 00:33
Hey there! Thank you for the detailed bug report.

This doesn't seem like it at first, but it's a duplicate of #790 so I'm closing it.

The workaround for now is to disable the `evaluate` option but it will have other negative consequences.

**Closed** 2020-08-18 00:33 UTC
