### ISSUE TITLE
Terser doesn't remove / includes empty comments

### ISSUE THREAD

**Issue by ForsakenHarmony** [terser/terser#353] opened 2019-05-28 22:51 UTC
**Bug report or Feature request?**

Bug?

**Version (complete output of `terser -V` or specific git commit)**

4.0.0

**Complete CLI command or `minify()` options used**

`./node_modules/.bin/terser --comments "[@#]__PURE__" ./file.js`

**`terser` input**

`file.js`
```
exports.MyClass=
/* */
function(){function o(){}return o.prototype.foo=function(){return Promise.resolve()},o}();
```

**`terser` output or error**

Same as input

**Expected result**

No comments

**More Context**

https://travis-ci.org/developit/microbundle/builds/538469823

Was thrown off by these logs, we have the regex as the comments option

**Comment by fabiosantoscode** [comment] 2019-06-01 18:48
Interesting. Thanks for the report!

**Comment by edoardocavazza** [comment] 2019-11-15 15:37
Hi @fabiosantoscode ! Any news about this issue? Can I help some way?

**Comment by fabiosantoscode** [comment] 2019-11-18 08:31
Hey! This one is a bit low priority, and more serious bugs have been popping up.

If you want to help, you can try to investigate why this is happening. The file you're looking for is lib/output.js

That said, I think that `__PURE__` comments are already removed by default. So you might want to try that too.

**Comment by jridgewell** [comment] 2021-09-06 23:58
Closing as a duplicate of https://github.com/terser/terser/issues/526, fixed in https://github.com/terser/terser/pull/550.

**Closed by jridgewell** 2021-09-06 23:58 UTC
Labels: suboptimal-output
